### ISSUE TITLE
question about cp

### ISSUE THREAD

**Issue by jvmk** [odeke-em/drive#1061]
Hello,

Thank you for making this nifty tool available.

I tried to use `drive cp 'Some Root Folder'` to copy the directory structure of a remote folder named 'Some Root Folder' to my local machine. It seems I misunderstood this command. What this actually does is that it copies a remote folder to some other remote folder - correct? So in my case it would place a copy of 'Some Root Folder' in my Google Drive root - correct?

The only output I got was:

```
Processing...
copy: //Some Google Sites Website: Some Google Sites Website is non-copyable
```

where 'Some Google Sites Website' was at the path 'Some Root Folder/Some Google Sites Website'

...and I (mistakenly) thought the call was hanging due to the error message as it just stayed there forever, so I eventually terminated it with Ctrl+C.

Couple of stupid questions, please as I am super concerned I messed up the shared folder I was trying to copy:
1. Can I safely delete the copy of 'Some Root Folder' from my Google Drive Home without affecting the original? The original is a shared folder, so I obviously don't want to trash other people's files.
2. Could the fact that I terminated the operation with Ctrl+C have had any damaging effect other than leaving some files in the copied folder in an incomplete state?
3. What's with the output for the Google Sites file? How come Google Sites files can't be copied?

Thank you.

**Comment by odeke-em** [comment]
Thank you for the question @jvmk and welcome to drive!

So indeed some files can be declared non-copyable.

>1. Can I safely delete the copy of 'Some Root Folder' from my Google Drive Home without affecting the original? The original is a shared folder, so I obviously don't want to trash other people's files.

So if you manually invoked "Add to my Drive" from https://support.google.com/drive/answer/2375057?co=GENIE.Platform%3DDesktop&hl=en then yes you can safely remove it. Otherwise I'd advise you don't do that.

>2. Could the fact that I terminated the operation with Ctrl+C have had any damaging effect other than leaving some files in the copied folder in an incomplete state?

A Ctrl-C kills the connection locally and then the connection is killed on Google Drive which recognizes that due to non-completion and broken connections. Uncompleted operations on Google Drive will be garbage collected so I don't think so.

>3. What's with the output for the Google Sites file? How come Google Sites files can't be copied?

Am not sure what the output should be but Google Drive allows some things to not be copyable or even downloadable, say for example to curb plagiarism, confidential content, to deal with embargoes etc.

Hope that answered your questions and for now I'll close this issue but please feel free to circle back in case of anything. Thank you!
