### ISSUE TITLE
where to find files that were uploaded to google drive

### ISSUE THREAD

**Issue by evanycgeng** [odeke-em/drive#1072]
Hi,

Can someone explain where can we find files that were uploaded to google drive. I am using a google service account but I cannot find files on the google drive with same email for google service account.

Thanks!

**Comment by odeke-em** [comment]
Hello @evanycgeng, thank you for this question!

So:
a) firstly run `drive about`
which will give you some information about the account to help you know which account you are using
b) run `drive id .`
which will print out for you the drive folder ID such as
```shell
$ drive id .
FileId                                           Relative Path
"0PYuk6aZd4RTPUk2MVQ"                            "/"
```

and once you have that folder ID, you can now go to `https://drive.google.com/drive/u/<account_value>/folders/<folder_id>`
where `<account_value>` is the number related to your credentials in the Web UI (and from step a)) and `<folder_id>` is the ID of the home folder e.g. https://drive.google.com/drive/u/1/folders/0PYuk6aZd4RTPUk2MVQ

Hope that helps. I shall close this issue since I've answered that question but please feel free to ping back here in case of any questions or anything. Thank you!
