### ISSUE TITLE
Doing pull and push

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#11]
1. I did a previous initial push using rakyll's drive. I do a push on the same dir using your drive and it seems to want to do the same initial push (I can't tell because there are a lot of files and I can't scroll back ijn history).

2. As well, if I do a pull on a remote dir (previously using rakyll) to check that all files are synced and your drive tells me that it should be pulled using the 'M' flag where this file hasn't been changed in months locally and/or remotely. I understand the 'Last Modified' date on google drive will be when the rakyll push was pushed, but this should not be the case for an initial push as per comments on https://github.com/rakyll/drive/issues/50. This should be the same as `cp -p` when copying files.

3. I have a remote dir which exists but doing pull commands keep asking for the same files over and over. I'm not sure why as the files havent changed and I'm not accessing them in any way.

**Comment by odeke-em** [comment]
@ikwyl6 could you try this with the latest?

**Comment by odeke-em** [comment]
@ikwyl6 So here is the reason why this issue existed:
 If you have a Google Doc or Sheet, they don't provide a url to download the raw data but can only be exported. However, to maintain consistency we must touch an empty file locally for a Google Doc + Sheet due to the explanation above and this file gets skipped when pushing upstream.
The implication then is that when doing a pull however, the sizes of the files do not match up and that's why there was always a change here. If you are interested in seeing the implementation it is here: https://github.com/odeke-em/drive/commit/3c2c974940202853a7199ebe91b4b3449acac5fa

**Comment by ikwyl6** [comment]
How about making the Google Doc a link file? So when clicked in a linux file browser it will open up using 'xdg-open' ? Atleast it lets the user know the file still exists and they can edit it on the spot if clicked..

I will get the latest and report back.

**Comment by odeke-em** [comment]
So currently drive supports for exporting of files see: https://github.com/odeke-em/wiki_content/blob/master/drive/export_usage.png

**Comment by ikwyl6** [comment]
For my 01 item above, this is still happening but instead of the whole folder about 15-20% is still being requested to be added '+' . Is there a debug flag I can show to give you more info? These are all jpgs and some avis.

When I still proceed with this 15-20% of the files that are not uploaded, I try to do a `drive pull` to verify all if good on the remote side but it says to remove it locally ('-' minus symbol). Going on google drive (chrome), there are no files present even though they should have been uploaded. Since I do want these files pushed to GD, I have done the push but it throws an error: http://paste2.org/UIVvHNY2

Should this comment be a separate issue? Let me know.

**Comment by ikwyl6** [comment]
@odeke-em ?? Dis you need more info from me? Did you make a change that is reflective of this issue that you want me to try out? I see milestone changes only above.

**Comment by odeke-em** [comment]
@ikwyl6 the error that you got was a separate issue that you already filed. Basically it was a resource exhaustion due to too many threads being spawned. Did you pull from master and retry it?
See the issue you filled for #11 is way separate from the resource exhaustion issue and is more related to correctness and the issues carried over from rakyll's repo.
