### ISSUE TITLE
Push in Bg

### ISSUE THREAD

**Issue by LordBli** [odeke-em/drive#1100]
Hi everyone !

I'm using ngrok to access to my server by ssh. 
Here is the thing, the connection is limited. So I would like to use the push command in background, is it possible ?

Best Regards

**Comment by tukusejssirs** [comment]
@LordBli, I am not sure if I understand you correctly, but in Bash, you can append `&` to any command in order to run that command in background. List of backgrounded commands (called jobs) you can run `jobs`, where each command gets a number (starting from `1`) using which you can access it. Note that is `--no-prompt` `drive` command option that is used to auto-accept all changes. For example: `drive push --no-prompt &`

When you want to put the job to the foreground, you can use `fg` command optionally followed by the number from `jobs` command output. When no number is used, the _the shell's notion of the current job_ is used (usually the last job, the one with highest number).

---

Using `&` still output the backgrounded command output. If you don’t want to see the output, you can use `&> /dev/null`, i.e. redirect both `stdout` and `stderr` to `/dev/null` (which in this case behaves like a black hole) and the follows the `&`. Note that even you put such backgrounded command to foreground, no output will be output. For example: `drive push --no-prompt &> /dev/null &`

---

However, when your SSH connection disconnects, such jobs will be terminated, which I think you don’t want.

You have two options:
1. you can use a terminal multiplexer / screen manager like `tmux` or screen` (search their usage on the Internet);
2. `disown` the jobs.

The second option is quite easy: run `disown` optionally followed by the number from `jobs`. It essentially (not actually) transfers the ownership from the user you are currently logged in and it will make the job keep running (if the job won’t exit/terminate by other means) even when the user you are currently logged in, logs out (e.g. when the SSH session ends). Of course, it will be terminated when the computer/server is shut down. For example:

```bash
# On one line
drive push --no-prompt &> /dev/null & disown

# One separate lines
drive push --no-prompt &> /dev/null &
disown
```

---

Running processes (jobs/commands) you can still see using many utilities monitoring processes:
- `ps` (e.g. `ps aux | grep 'command name or whole command'`);
- `top` or `htop`.

**Comment by LordBli** [comment]
Most expected answer ! Thanks a lot. 
Your answer is juste what I needed !
