### ISSUE TITLE
[feature request] prevent clashing files from being erased

### ISSUE THREAD

**Issue by jxerome** [odeke-em/drive#156]
Drive allow a directory to have several files with the same name.
In that case one of the file is overriden by the other when pulling.
When pushing the data of the second file is replaced by that of the other in the drive server.

I got the problem with one odt file with it's gdoc sibling that had the same name. The odt content was replaced by the "gdoc link" text info created on my desktop by drive.

**Comment by odeke-em** [comment]
Hello @jxerome thank you for reporting this and welcome to drive, since this is our first interaction.

Yes in deed, this behaviour is expected so far at least because your file system most definitely does not handle clashing file names in the same folder/directory but Google Drive can handle this. It is this kind of behaviour that allows for one to edit and push files and make sure that they modify the same file. It is also mentioned in the README. There is a sort of safe mode that you can use to avoid clobbering of files `--no-clobber` just in case these files are tripping you out.

Please let me know what you think.
Thanks.

**Comment by jxerome** [comment]
Hello,

Thanks for your answer and your welcome message.

I think that data safety should not be an option, or at least should be the default behaviour.

I opened this issue because due to this behaviour I deleted content of a file shared with me by my coworkers. I was finally able to restore the data but that could have lead to really problematic situation.

I don't know a desktop file system that would make the difference between two files with the same name (and same case). So this is a common case.

I see two case.

1/ The official Windows and mac drive synchronized add extensions like '.gdoc'. That make it easier to use files localy. And it whould have gives files different names in my case.

2/ In more general case, in case of name conflit, only one of the file is downloaded. When pushed, it should only affect the file it comes from. Not the other one. "Sync" should be based on googles id and not names. Id's that could be cached in your .gd dir.

**Comment by odeke-em** [comment]
Thanks for the response. I'll respond in about 5 hours when I get back home.

**Comment by odeke-em** [comment]
Hello @jxerome thank you for the great suggestions. Sorry for the late reply, I forgot about this.

`1/ The official Windows and mac drive synchronized add extensions like '.gdoc`

That's great when you have a client that actively monitors retains mapping in a DB, but as soon as we use a non-sync-active client such as drive, this can quickly get out of hand. Adding .gdoc to every file on its own creates other files that will need a mapping, as well as lookups and maintaining such results in a DB. drive already caches meta info in .gd/indices/ per file to use for conflict resolution etc. Pushing later on will involve looking for these paths etc.
 See it can be done locally but I'd prefer to wait for a couple of incoming changes to deal with searches by FileId(as you'd guess this radically changes the lookup mechanism) plus also fully understanding the expectations. If you'd like a PR would be welcome :) otherwise I'll be experimenting with the mentioned upcoming changes.

**Comment by jonbrock** [comment]
Continuing the discussion from #287 you said "Sure stripping out the parenthesis in brackets sounds like a plan but what happens if a user already has such on their drive? I'll explore the idea more."

That is a good point. I don't know enough about the drive API to know all the options, so I'm going to take some time to experiment with it. Unfortunately I don't know Go at all!

**Comment by odeke-em** [comment]
No worries about that @jonbrock, thought experiments are as good as code contributions ;) Your suggestions are actually good ideas to getting this in, I'll explore this more too. Please let me know what you think about the simple file system idea.

**Comment by canpolat** [comment]
Subscribing.

**Comment by odeke-em** [comment]
There is now clash auto renaming in drive. Thanks for reporting this issue and please reopen I it persists.
