### ISSUE TITLE
Error msg when outside of $GDRIVE directory

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#161]
The error message when you are outside of your $GOOGLE_DRIVE directory:

`no gd context is found; use gd init`

should be 'nicer' or give more info. Something like 'You are outside your google drive that was set by 'drive init'. Please change to that or one of its children directories and perform this command'.

I came across this error because I was in a symlinked dir but not under the $GOOGLE_DRIVE/symlinkdir but under '/symlinkdir' itself and it threw this command.

Just a suggestion.

**Comment by odeke-em** [comment]
Hello @ikwyl6, thanks for reporting this. I totally agree a good error message would be great.

If you'd like to submit a PR because I'd love for your contributions to be recognized (that you've been doing for quite a while), we can walk through the PR together, it should be a one liner. Otherwise, let me know and I'll consult you on the appropriate message.

Please let me know if this makes sense.

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/188
