### ISSUE TITLE
"400 Bad Request" for authorization code

### ISSUE THREAD

**Issue by aselvan** [odeke-em/drive#162]
I am getting a "400 Bad Request"  when attempting to visit the URL created by running "drive init ~/gdrive" to get the authorization code.

Any ideas?

NOTE: I installed the latest drive by running  "go get -u github.com/odeke-em/drive/cmd/drive"

**Comment by odeke-em** [comment]
Hello @aselvan welcome to drive since this is our first interaction and also thank you for reporting this.

I cannot seem to reproduce this, I just did a fresh install on another computer and successfully run a drive init. Please make sure you provide the right access if you are comfortable with giving drive access to your Google drive, then please proceed, otherwise you might get that error otherwise.

Please let me know if this makes sense.

**Comment by aselvan** [comment]
@odeke-em, thanks for your immediate response :+1: 
When I paste the URL generated by the 'init' command in the browser, I don't go any further and get  400 immediately. In other words, I have not made it to the point where you can select drive access permission. Will do some more tests to see if I can figure out what is going on.

**Comment by odeke-em** [comment]
Oh I see.
It might sound like a ridiculous suggestion but would you mind trying
```shell
$ ping accounts.google.com
```
and then once that succeeds, just make sure you can visit https://accounts.google.com.
If that fails, then it might be some settings or bad cookie cached on your computer.
Hope this helps

**Comment by aselvan** [comment]
Thanks for your help. It was indeed some cached stuff in my chromium on ubuntu desktop. I used my macbook to get the authorization key and is all good now.

**Comment by odeke-em** [comment]
Good to know you've been able to resolve that :) Please don't hesitate to reach out in case of any issues or ideas.
