### ISSUE TITLE
Problem with .desktop links

### ISSUE THREAD

**Issue by Queuecumber** [odeke-em/drive#165]
When I pull files down from my google drive, it looks like the drive client tries to make .desktop links to the file. However, it gives these files no extension so Nautilus doesn't seem to know what to do with them. Double clicking the files opens them for editing in gedit (the .desktop file itself). If I manually rename the file to add the .desktop file extension,then the icon loads and double clicking takes me to edit or view the file in chrome as expected. Is this a setting I missed or a bug?

**Comment by shaggytwodope** [comment]
@Queuecumber The extension issue aside, how are you installing drive?

**Comment by Queuecumber** [comment]
Through the ppa

**Comment by shaggytwodope** [comment]
@Queuecumber Ok so I think the extension issue is all on @odeke-em. The Icon's may also need to be resized... I'll talk to @odeke-em about that later. So in short it's a bug, but the icons display properly after adding .desktop to the files? (I ask this because I'm the guy packaging for the ppa.)

**Comment by odeke-em** [comment]
Ama let you finish @shaggytwodope but ... #kanyemoment just kidding haha.
Anyways, @Queuecumber thank you for reporting this and @shaggytwodope thank you for the response.
For sure this is a bug. Weird thing is that on my Ubuntu installations no configuration seems to work so I haven't put in work on the file configurations mostly because I don't know what am doing with the desktop files. However since this is an issue, I will do some more experimentation and then will consult with you and @shaggytwodope. Any ideas and help will definitely be useful :)

**Comment by dgvirtual** [comment]
As I have reported in my experiment [here](
https://github.com/odeke-em/drive/issues/74#issuecomment-87616635), this is
the behaviour of Nautilus, although, not the behaviour of half the other
file managers, that do recognize the *.desktop file for what it is even
without extension.

Now, I would hesitate to say for certain it is a bug in Nautilus. the
"file" command reports that an extensionless desktop file is a text file:

    $ file --mime-type -b DesktopFileNoExtension
    text/plain
    $ file -b DesktopFileNoExtension
    ASCII text

While the xdg-mime reports it is a desktop file:

    $ xdg-mime query filetype DesktopFileNoExtension
    application/x-desktop

There might be different methods for determining file types of files in
file managers on Linux. It is known that on Windows it is done purely by
extension. On Linux the preferred method is by investigating the beginning
of file content, but extension is still used in some cases. And still, we
see that there is a difference on how different programs report file mime
type (file v. xdg-mime). So it is possible that Nautilus simply uses a
different scheme (and has it's reasons). Or maybe they really do not have
any reason for this, and maybe they would gladly change the behaviour of
Nautilus if somebody asks.

The easiest way to figure those things out is to file a bug report against
Nautilus and see what happens. :)


2015-04-28 6:45 GMT+03:00 Emmanuel Odeke <notifications@github.com>:

**Comment by odeke-em** [comment]
Hello @dgvirtual thank you for chiming in. Would you and @shaggytwodope mind adopting this issue if you've got time? -- since the both of you seem to be knowledgeable in this area

**Comment by Queuecumber** [comment]
thanks for looking at this guys, the icons look fine to me once I add the .desktop extension

**Comment by shaggytwodope** [comment]
@odeke-em Not entirely sure how it's meant to work. But when the filenames are generated they need the extension .desktop in some file managers. And in some cases need to be executable before displaying an icon. May also need to re-size some of the icons. 128x128 doesn't show in all file managers. (I'm thinking maybe using svg?) Why do icon's make things harder lol.

BTW @odeke-em  #kanyemoment me again .... I'll #bieberroast you lol.

**Comment by odeke-em** [comment]
@Queuecumber what file manager do you use? Same here if I add the .desktop extension it works with Nautilus.
@shaggytwodope oh okay that is tricky then, I'll do some experimenting with it over the weekend. Haha you should checkout the roast of Charlie Sheen or Donald Trump, hilarious ones.

Otherwise, I'll try to spin up a PR to try to fix this over the weekend.
Thank you folks for your help and patience.

**Comment by dgvirtual** [comment]
@shaggytwodope, you mention three issues: 

  - when the filenames are generated they need the extension .desktop in some file managers

that is true of Thunar and Nautilus (not true of Dolphin, Konqueror, PCmanFM); The simple way to solve this would be to add the "desktop" extension. The harder way would be to file bug reports for Thunar and Nautilus, and see if the lack of magic file type recognition for *.desktop files is intentional or is it a bug. Could some Thunar or Nautilus user do that?

  - in some cases need to be executable before displaying an icon

In my tests it might have been true for Thunar file manager, as it did not display the icons on unexecutable *.desktop files. But I did not try to make them executable to see if icons are displayed then. The problem was that on Nautilus and Thunar the links without the executable permission would not open at once, they would display a warning about the executable bit not set, allowing the user to choose whether to (if I remember correctly) set the executable bit, execute the file anyway or abort the operation. I cannot see why the file manager would be so cautious, and I would not object to having the desktop files executable... But there has always been a mood in Linux circles not to give executable bit to files that are in no need for it. Do not know why exactly that might be dangerous... :) In other words, I have no opinion on this, but would not object to making all *desktop files executable.

  - May also need to re-size some of the icons. 128x128 doesn't show in all file managers. (I'm thinking maybe using svg?) 

In my tests the icons would be autoresized by the file manager if they are placed directly in /usr/share/images or ~/.local/share/images/ . If they are placed, as they are in the ppa package, in /usr/share/icons/hicolor/*/mimetype/ , it may not be enough to have them in 128x128/mimetypes subfolder, they may have to be resized and placed into every subfolder (16x16, 32x32, 64x64, 256x256, etc.)  I have made the [full icon set](https://drive.google.com/open?id=0B7N4UaoQWBXicHNSS1BZa2hOYms&authuser=0) except for the svg icons - could you test if it works for you? And of course, the svg's would be nice too, they would also make for better "source" files than the current gimp xcf's, but that would take me some time, I am not very good at using Inkscape.

**Comment by IS-smcleod** [comment]
As far as I can tell, Thunar uses MIME types for opening files without extensions.

If anyone is worried about making desktop files executable, it could be made into a configuration open.

**Comment by odeke-em** [comment]
Hey folks please take a look at https://github.com/odeke-em/drive/pull/195.

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/195. Please re-open if persists.
Thank you for raising this issue!

**Comment by Queuecumber** [comment]
Wow thanks a lot for the fast turnaround on this guys
