### ISSUE TITLE
List Shared with Me files

### ISSUE THREAD

**Issue by csaleman** [odeke-em/drive#187]
Hi, I haven't been able to list the files/directories in "Shared with me" and not yet added to "My Drive".  There is any method to "Add to my Drive"?

#drive list -shared
#drive list 
both return the same list.

-----
drive version: 0.2.0
Commit Hash: '6d9751a9333cce78d0ccfe7504a4e47bdcf5f2a6'
Go Version: go1.2.1
OS: linux/amd64

**Comment by odeke-em** [comment]
Hello @csaleman, thank you for reporting this and welcome to drive!

Good catch. Yes I intentionally turned this off as you'll see in src/list.go. But that was because I needed to properly implement listing of shared folders, the traversal works alright, just the actual printing.
I will take a look at this in about 10 hours when I get back home.

**Comment by odeke-em** [comment]
PR https://github.com/odeke-em/drive/pull/189 addresses this. Just doesn't yet have searching for shared files by matches, otherwise by plain traversal and listing, the PR adresses it.

**Comment by csaleman** [comment]
Thank you !! I just now wonder how to pull from a shared that has not been added to my drive yet.

**Comment by odeke-em** [comment]
Good point, so I'll be adding a feature to pull shared as well as pulling by id. However, pull shared with me is a little tricky because the pull and push operations are centric to content owned by you, so pulling in shared folders might be a little tricky unless it is explicitly annotated. We'll think of something. Please open a separate issue and we can work on it there.
Thank you for raising this!

**Comment by odeke-em** [comment]
@csaleman I've implemented operations by Id (e.g pull --id) in PR https://github.com/odeke-em/drive/pull/200 and the latest can be found on master.
