### ISSUE TITLE
[pull] message on encountering conflicts is confusing.

### ISSUE THREAD

**Issue by tioteath** [odeke-em/drive#222]
Steps to reproduce:
```
$ drive init ~/Cloud
$ cd ~/Cloud
$ drive pull
```
Output by `drive pull`:
```
Resolving...
X /My Tracks/...
X /My Tracks/...
X /My Tracks/...
X /My Tracks/...
X /My Tracks/...
X /My Tracks/...
X /My Tracks/...
X /My Tracks/...
X /My Tracks/...
X /My Tracks/...
X /My Tracks/...
Everything is up-to-date.
```

That's it. No files are transferred, directory stays empty (`~/Cloud/.gd` is created, though). No output shown, except provided above. Cannot add additional info, as no `--debug` or `--verbose` options provided.

**Comment by odeke-em** [comment]
Hello @tioteath, thank you for reporting this and welcome to drive! 

So doesn't drive show you that you have clashing file names right there with the X's? 
There are a couple of reasons why it won't pull with conflicts e.g in the README and mainly due to the confusion previously encountered with the file system expecting unique file names within a dir but Google Drive allows for clashing names within the same dir. This confusion has plagued users quite a lot.
Also `drive version`? 
Btw there are ways to turn of rejection of clashing file names

**Comment by tioteath** [comment]
> So doesn't drive show you that you have clashing file names right there with the X's? 

Well, according to the message this is hard to understand what's going on exactly. Message kind of "File clash detected, aborting" would be helpful. The message "Everything is up-to-date." is especially confusing, as it definitely not up-to-date. Mainly because of that message I've decided that `drive` misbehaves.

> Also drive version? 

```
drive version
drive version: 0.2.3
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
```

**Comment by odeke-em** [comment]
Wait, so you didn't get "Clashes detected"?

**Comment by tioteath** [comment]
No, not really. I posted above exact message I've got, except I replaced filename with '...'. But you're right, clashes was the problem.

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/244. Thank you for reporting this.
