### ISSUE TITLE
Error 54 on installation

### ISSUE THREAD

**Issue by Issam2204** [odeke-em/drive#223]
Hello, Im encoutering an error on installation:

issam@localhost:~$ go get -u github.com/odeke-em/drive/cmd/drive
 google.golang.org/cloud/compute/metadata
.go/src/google.golang.org/cloud/compute/metadata/metadata.go:54: unknown net.Dialer field 'KeepAlive' in struct literal

**Comment by odeke-em** [comment]
Hello again @Issam2204. Unfortunately that's an issue with the Google Cloud package that I have no control over since it is a repo not even connected to drive and that they are continually building. To get around this, just go into $GOPATH/src/github.com/odeke-em/drive and then do a git pull origin master and then the go get like this:

```shell
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git pull origin master && go get github.com/odeke-em/drive/drive-gen && drive-gen
```
Hope that helps.

**Comment by Issam2204** [comment]
Unfortunately the error is still there.

I'll simply try again later. Thank you again odeke-em!

**Comment by odeke-em** [comment]
Oh btw what version of go are you using? I always build go from source and that seems like they were using the latest code from Go tip. I'd like to help spin up a custom clone and make sure that previous go versions will build but right now am in quite a bit of crunch time here :( However, hopefully the GoogleCloudPlatform team will realize this since a whole bunch of packages rely on it and they can patch something up in the next few hours. Otherwise, I'll take a look at it in about 9 hours when I get free time.

**Comment by Issam2204** [comment]
go version go1.2.1 linux/amd64

Again, thank you! Pretty confident Google will fix it soon :)

**Comment by odeke-em** [comment]
Yes in deed, hopefully! Just looked through their tests and they are having a couple of build errors. Catch you in a few hours and hopefully then we'll all be smiles and able to build :)

**Comment by kleptog** [comment]
I have the same version of go and I am getting the same error while building. Apparently they havn't fixed it yet?

Is there a released known working binary somewhere I can download?

**Comment by Issam2204** [comment]
I confirm the error is still there.

**Comment by odeke-em** [comment]
@kleptog please give me your OS specs and I can compile a binary for you. The only caveat is that my linux/amd64 machine got messed up and I needed to order a part to fix it. Otherwise I have darwin64, linux32, arm32/64 machines. I guess I could spin up VMS as well but that'll be later. Thanks for the patience, and I guess since Google hasn't yet fixed it, I'll have to dive in soon and try to fix it.

**Comment by kleptog** [comment]
Ubuntu Trusty 14.04 (LTS), but any amd64 binary should do, Go compiles all static binaries iirc.

**Comment by odeke-em** [comment]
Oh okay, please see https://github.com/odeke-em/drive/releases/tag/v0.2.4#binaries you should find a binary at the bottom, and to verify its integrity after download sha256sum the download and the details for version as well.

**Comment by odeke-em** [comment]
Any luck?

**Comment by kleptog** [comment]
Well, it turns not out just any amd64 binary. I tried it and it wouldn't run, it says it's a "Mach-O 64-bit x86_64 executable" which I guess is for MacOS? I'd need a Linux binary.

I'm not totally clear on the problem though. Are you suggesting above that if I had a newer version of Go it would work? Is there a newer release I can try that might work?

Thanks for the effort so far.

**Comment by odeke-em** [comment]
I thought so, binaries are built for specific architectures. Yes if you got go1.4 you can build it. Same release will work if built. You can build go from source by following instructions from here https://golang.org/doc/install/source. Otherwise I'll try to spin to spin up a VM for linux/amd64.

**Comment by kleptog** [comment]
What I ended up doing was installing the [go 1.4 PPA](https://launchpad.net/~evarlast/+archive/ubuntu/golang1.4) and then it builds fine. That's definitely a solution for Ubuntu users anyway.

**Comment by odeke-em** [comment]
Cool, thanks @kleptog for sharing that.

**Comment by smarthimandrew** [comment]
@odeke-em I ran into this issue while following the readme instructions. Should this issue be temporarily noted there?

**Comment by smarthimandrew** [comment]
I was unable to get @kleptog 's solution to work. Installing go 1.4.2 from https://golang.org/dl/ helped me.

I'm running Ubuntu 12.04 i386

**Comment by odeke-em** [comment]
Thank you @smarthimandrew for reminding me, I've updated the README to show the minimum now is go1.4. I'll dig in more sometime and if I can help get us back to 1.2 then I'll revert the minimum version to 1.2 or so.

**Comment by odeke-em** [comment]
Updated in the README. Thank you for reporting this.
