### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by asd-and-Rizzo** [odeke-em/drive#238]
Added `go` to system as described, but failed then with `gcc`.

I.e. `go get -u github.com/odeke-em/drive/cmd/drive`
 fails with next:
```
# github.com/odeke-em/drive/src
exec: "gcc": executable file not found in %PATH%
```

Not sure, but `go` as I heard designed to be compiled during installation or first run (and replace scripting languages for many purposes). Not sure same is about `c`. 

Is it possible to drop need of `gcc` or produce precompiled windows binary?

**Comment by odeke-em** [comment]
Hello @asd-and-Rizzo and welcome to drive. Thank you for reporting this issue.

So, this seems more like an issue to do with go than with drive. drive's installation just uses go's tools.  Please make sure you are installing go for Windows and not the *NIXes.

`Is it possible to drop need of gcc or produce precompiled windows binary?`
I haven't used Windows in ages nor used it for any serious work and as mentioned in the README of this project https://github.com/odeke-em/drive#known-issues, drive probably doesn't work on Windows. 
Due to lack of Windows machines I couldn't be able to build nor compile binaries, however I'd love to help out. If you can get things compiling on Windows please feel free to share your steps :)

In the future if running on Windows is considered a strong need, then I'll just have to comb through the project making sure all the relative paths translate automatically to the host OS ie the Windows path separator in your case: '/' for *NIX vs '\\' for Windows.

**Comment by asd-and-Rizzo** [comment]
Installed from `https://chocolatey.org/packages/golang` and added `go` related environment  variables GOPATH and appended `go` `bin` to PATH. Seems need to install `GCC` for compilation to proceed.

**Comment by odeke-em** [comment]
and you can `go get` other packages alright?

**Comment by asd-and-Rizzo** [comment]
Tried other repos. `go get` without errors.
```
C:\Program Files\Far Manager>go get github.com/golang/protobuf
package github.com/golang/protobuf
        imports github.com/golang/protobuf
        imports github.com/golang/protobuf: no buildable Go source files in C:\tools\go\src\github.com\golang\protobuf
C:\Program Files\Far Manager>go get github.com/golang/protobuf/proto
C:\Program Files\Far Manager>go get github.com/golang/protobuf/proto
C:\Program Files\Far Manager>go get github.com/emicklei/go-restful
C:\Program Files\Far Manager>
```

**Comment by asd-and-Rizzo** [comment]
Actually I am here because dislike default Google Drive for windows. And have next options like install `gcc` and try to build this. Or there seems alternative drive client like `prasmussen/gdrive` which has build executable for windows.

**Comment by odeke-em** [comment]
I see, it could be something to do with the cgo checks for tty flushing. However, Iet me ask someone more knowledgable in that area and is on the Go team. /cc @minux: hey @minux I kindly wanted to ask that if you aren't busy, might you have any insights into this issue? -- Thanks.

**Comment by ptman** [comment]
Maybe crosscompiling for Windows from Linux would be easier?

**Comment by odeke-em** [comment]
Great idea @ptman thanks. This is a good start. However, there are quite a number of things that aren't going to work well with Windows. For starters the path resolution, secondly hidden files.

**Comment by Walkman100** [comment]
Windows doesn't care what seperator you use - you can use `/`'s as much as you like, and almost everything will still behave as usual, unless you are in a bash or cygwin shell.

**Comment by odeke-em** [comment]
Oh okay, thanks for that information @Walkman100. So in this case, cross compiling is left to be tested? A friend who works at Microsoft, in a casual discussion just informed me that apparently even in bash or cygwin it should work alright, even though cygwin will still complain.

If someone has a chance to experiment, you could cross compile with something like this:
```shell
$ GOOS=windows GOARCH=<your_architecture>  go get github.com/odeke-em/drive/cmd/drive
```

**Comment by asd-and-Rizzo** [comment]
I tried this on `cygwin` for windows 7 all are 64 bit and failed
```
Dzmitry_Lahoda@PC ~
$ GOOS=windows GOARCH=amd64 go get github.com/odeke-em/drive/cmd/drive
# github.com/odeke-em/drive/src
/usr/lib/gcc/x86_64-pc-cygwin/4.9.3/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-cygwin/4.9.3/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

Dzmitry_Lahoda@PC ~
$ gcc
gcc: fatal error: no input files
compilation terminated.

Dzmitry_Lahoda@PC ~
$ go test
can't load package: package .: no buildable Go source files in C:\tools\cygwin\home\Dzmitry_Lahoda

Dzmitry_Lahoda@PC ~
$ git test
git: 'test' is not a git command. See 'git --help'.

Did you mean this?
        reset

```

**Comment by pefoley2** [comment]
I was able to build drive successfully on windows with CGO_ENABLED=0 go get -u github.com/odeke-em/drive/cmd/drive

**Comment by odeke-em** [comment]
@asd-and-Rizzo and everyone, @pefoley2 was able to build it as specified. I'll be closing this issue soon.

**Comment by pefoley2** [comment]
See step-by-step directions at https://github.com/odeke-em/drive/wiki/Building-on-Windows

**Comment by odeke-em** [comment]
Thank you @pefoley2 for solving this. Cheers, and thank you all for the discussion.

**Comment by powerunlimited** [comment]
getting this error when following the wiki
```
C:\Go_WORK>go get -u github.com/odeke-em/drive/cmd/drive
# cd C:\Go_WORK\src\google.golang.org\api; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package google.golang.org/api/drive/v2: exit status 1
package google.golang.org/api/googleapi: cannot find package "google.golang.org/api/googleapi" in any of:
        C:\Go\src\google.golang.org\api\googleapi (from $GOROOT)
        C:\Go_WORK\src\google.golang.org\api\googleapi (from $GOPATH)
```

**Comment by odeke-em** [comment]
Hello @powerunlimited welcome to drive!

So that's a trip that I've found occasionally with Go: I'd have asked, is your $GOPATH properly setup but it actually looks like it is already properly setup. I am going to give you a terrible solution that I've used because digging into why Go trips out is quite a bit of work:
You can alleviate this by removing
+ $GOPATH/src/google.golang.org
+ $GOPATH/src/github.com/odeke-em

and then starting afresh
with
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by powerunlimited** [comment]
@odeke-em Hi,
sorry for the late reply, I tried your solution, and to my surprise it actually worked.
thanks a bunch
I guess sometimes starting over is the easiest solution.
