### ISSUE TITLE
Is help intended to go to `stderr`?

### ISSUE THREAD

**Issue by utgarda** [odeke-em/drive#260]
```ShellSession
$ drive pull -h | grep prompt
Usage of drive pull:
  -exclude-ops="": exclude operations
...
*** all this is stderr output ***
...
  -skip-mime="": skip elements with mimeTypes derived from these extensison
$ drive pull -h 2>&1 | grep prompt
  -no-prompt=false: shows no prompt before applying the pull action
```

**Comment by odeke-em** [comment]
Hello again @utgarda. Thank you for reporting this issue as I can see from a continuation of one you made earlier on.
The flag parsing output is actually done by an external package `command` and not actually by drive. I made a fork from github.com/rakyll/command now at github.com/odeke-em/command.
In regards to your question: since `flag -h` it is in an error-ed state, yes help output should go to stderr, as opposed to `drive help pull` which is just a normal functioning mode and a subcommand of a flag.

**Comment by utgarda** [comment]
Hi @odeke-em , 

but `drive help` tells us to use commands like `drive pull -h`:
```ConsoleSession
$ drive help
Name
        copy - copy remote paths to a destination
Name
        move - move files/folders
Description
        Moves files/folders between folders
* For usage flags: `drive move -h`
...
* For usage flags: `drive pull -h`
```
so I'm not sure if it's ok or not. Anyhow, I'm pretty sure it's not urgent. Unfortunately, I'm quite far from Go development, so all I can offer is these reports.

**Comment by odeke-em** [comment]
Oh yes it asks you to run `drive pull -h` but only because it is known that the parse will spew out whatever options. The list of options may grow or shrink but `-h` directly to the parser will give the list of options defined.
Thank you for the offer, no worries your input is quite useful. This is an interesting case because there doesn't seem to be a standard of sorts -- a bunch of commandline options send `-h` output to stderr, others send it to stdout. go seems to mostly treat `-h` output as help mode and `-h` sends output to stderr as well.
Otherwise, if we agreed on getting this to stdout, nothing would change in drive, it would however in the command parser which is an external package as I had mentioned earlier. It shouldn't be too hard to replace stderr with stdout.

**Comment by utgarda** [comment]
Alrighty then, now we know it :)

**Comment by odeke-em** [comment]
Would you mind opening this issue on my fork of command? This way I won't forget as am interested in us solving this issue. Thank you.

**Comment by odeke-em** [comment]
Hello @utgarda, thank you for reporting this issue. I fixed it in my fork of command with PR https://github.com/odeke-em/command/pull/2.
