### ISSUE TITLE
Problems with leap second?

### ISSUE THREAD

**Issue by philipp923** [odeke-em/drive#284]
Hi,
it seems I have problems with the time synchronization.
If I do a drive-google push there are thousands of files which are indicated as modified (Not all files in my drive). If I have a closer look at these files, they all have a time difference of exactly one second.

drive-google diff file.txt
* local:            2015-03-24T20:58:8.000Z                 
* remote:         2015-03-24T20:58:9.000Z 

If I confirm the push command, there are no files uploaded (~2kiB/s) but the process takes a lot of time. At the end everything is in sync again.

Has anybody else observed this behavior?

PS: Because I was not able to update the drive version 0.1.9, I did a new installation.
drive-google version 0.2.5
go version 1.4.2

Kind regards,
Philipp

**Comment by odeke-em** [comment]
Hello again @philipp923! That is just a needed time synchronization needed as well as now there is a database instead of raw files being created in your <your_drive_mount_path>/.gd/indices. The indices need to be added to the DB so that's what took the bulk of that time. So you can get rid of the .gd/indices path

**Comment by philipp923** [comment]
Hi odeke-em,
thanks for the very fast reply.
In this case I will execute the entire push and have some tea.

Regards,
Philipp

**Comment by odeke-em** [comment]
Cheers, enjoy that tea!
