### ISSUE TITLE
Pull without hidden, then push with hidden: data loss.

### ISSUE THREAD

**Issue by glebm** [odeke-em/drive#291]
Just did this:

```console
$ drive pull
$ drive push --hidden=true
```

My remote hidden files got deleted :(
Sounds like a bug to me.

**Comment by odeke-em** [comment]
Hello @glebm thank you for reporting this issue and welcome to drive.
To get started on this, let's untrash those files
```shell
$ drive untrash --matches <your_pattern>
```

Next, let's try that again:
```shell
$ drive push --hidden --exclude-ops delete
```

**Comment by odeke-em** [comment]
Also sorry that your first encounter was unpleasant :(

**Comment by glebm** [comment]
Thank you! Glad to learn my files are just trashed, not gone forever! :smile:. After this I've pulled with hidden files and all is good now!  This software is a life saver btw, thanks for working on it :+1:

**Comment by odeke-em** [comment]
Good to know that that worked for you. In the prompt, it gives a manifest of files to delete, so please take a look at that, also `exclude-ops` is an option that I like using. However, currently Google Drive remotely trashes items, but locally there isn't one yet.

**Comment by glebm** [comment]
Thanks, can't wait for .driverc as now I am a little afraid that one day I might forget the options and ignore the manifest. Do you consider this a bug that `drive push` would delete files that are not there because they haven't been checked out locally?

**Comment by odeke-em** [comment]
Yes in deed I agree, I got most of the work for the .driverc done but what's left is an awkward options parsing step for options because currently guess whether a default option was passed in or not. However, I'll try hacking on it again sometime this week and roll out something :)
In regards to deleting content that isn't available locally, this is intended behaviour and the way that your content can be properly mirrored.

**Comment by glebm** [comment]
Closing since it's intended behaviour. That does mean a user cannot safely work with just a subset of Drive files, but I guess it's out of scope for the moment.
