### ISSUE TITLE
Push to subfolder

### ISSUE THREAD

**Issue by BasvanH** [odeke-em/drive#297]
Hi,

I would like to push a folder with it's contents into a subfolder in drive.
Source: /initfolder/2015/test
So with a push in this folder, the folder named 'test' is created in drive's root, but not 2015/test. Init folder is set to /initfolder

How can I achieve this?

Regards,
Bastiaan

**Comment by odeke-em** [comment]
Hello @BasvanH, welcome to drive and thank you for reporting this issue!

If I may ask, is this literally `/initfolder/2015/test' relative to your filesystem's root '/' or '/initfolder/2015/test' relative to your Google Drive point e.g `~/my_drive/initfolder/2015/test'. 
* If the answer is the first case, I'd advise you to either make a symlink into your drive or check out push option `-m` (but `-m` is a bit flaky).
* If the answer is the second case, then please let me know your version because the desired behaviour is to maintain the hierarchy. I also can't seem to replicate your description.

To bundle information and get the version of drive running
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen && drive --version
```

**Comment by odeke-em** [comment]
Closing this issue as it was answered.
