### ISSUE TITLE
Parallelize uploads

### ISSUE THREAD

**Issue by Queatz** [odeke-em/drive#315]
I'm attempting to push 10GB of small files.  This leads to 1000+ hours in estimated time and <1% network bandwidth utilization.  It would be great if `drive` was smart about this and would either parallelize or something to speed up the process (maybe zip up batches of the files and then unzip them once on Drive.)

**Comment by odeke-em** [comment]
Hello @Queatz thanks for raising this issue and welcome to drive!

So, this is a known issue and I spun up something to fix that https://github.com/odeke-em/drive/pull/210. However that PR is over engineered, not well thought out and doesn't cut the deal. With the problems uncovered in testing it, I thought of a few simpler and better ideas this evening. Luckily I have the long weekend and might get started on hammering it out for the second time :)

**Comment by odeke-em** [comment]
Hello @Queatz, good news, I got fired up with trying to solve this and I am getting there. Please see branch https://github.com/odeke-em/drive/tree/easier-parallel-uploads and in particular commit https://github.com/odeke-em/drive/commit/9e5ac948f9f2a902f5cd6d8ad64d987498fd6ac9. It is a cleaner, simpler and better solution than the convoluted one I had produced some ages ago and was stuck try to hack on. However it isn't yet complete because now the task left is ensuring that `mkdirAll` calls  to the same path don't race each say `/a/b/cd` and `/a/b/cc` don't both a new create `/a/b` because they received a non-existant result at the same time. This is because Google Drive allows for same path, different fileIds but your OS won't allow for this. That's what is left to complete this up, otherwise I am able to test it out locally and things are sped up :)
For now am off to bed but when I get up I have some ideas and will get back to you.

**Comment by Queatz** [comment]
@odeke-em Awesome!  Would it be possible to just take care to create all the necessary folders in advance before firing off parallel jobs?  I'll be around this weekend.

**Comment by odeke-em** [comment]
I just got up. Now that's a great thought @Queatz :+1:

**Comment by odeke-em** [comment]
Hello again @Queatz, I've hacked up something but it still isn't right, the bane of my existance currently is Google Drive's UserLimitQuotas as well as the making sure that 'MkdirAll' calls remotely can only happen one at a time -- this I've been able to add in, but I'll need to test it well, seems to be working for now. To test out the stuff I've spun up:
```go
$ go get -u github.com/odeke-em/drive/cmd/drive
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git fetch --all && git checkout easier-parallel-uploads-caching
$ go get -u ./drive-gen && drive-gen
```

Thank you.

**Comment by Queatz** [comment]
Woot will give this a whirl now!

**Comment by odeke-em** [comment]
Aye aye. Hope it isn't too disappointing ;)

**Comment by Queatz** [comment]
Would I run the regular `drive` command after that?  It didn't seem too much faster with an initial test.

**Comment by odeke-em** [comment]
Yes in deed. That's because of the overhead of first sequentially creating directories. I have another branch on which it just starts the parallel uploads asap but it is unsafe right now because of the issues I mentioned with serialization. Today is a civic holiday so I might have some time to work more on it. Thanks for checking it out.

**Comment by odeke-em** [comment]
@Queatz please checkout out PR https://github.com/odeke-em/drive/pull/318. Fixed up a bunch of stuff and now should be better. Thank you for the patience.

**Comment by odeke-em** [comment]
Addressed by PR #318, please get the latest from master.  Thank you for reporting this.

**Comment by odeke-em** [comment]
Upload parallelized. Closing this issue, please re-open if it persists.

**Comment by Queatz** [comment]
Sweet, it's noticeably faster!  Thanks for looking into this so quickly! :+1:

**Comment by Queatz** [comment]
@odeke-em ok dude seriously this thing is flying, is there anything I can do for you?  How can I send you $50?  Do you ever make your way out to SF?  Can I buy you a drink?  `drive` is awesome, I spent 3 months fiddling with the official clients and other unofficial ones and couldn't get any to be up for the task, yet `drive` is just taking care of everything like a dream!  Couldn't end the day better than to come home and see it's still zapping them up! :smiley:

**Comment by odeke-em** [comment]
Thank you very much for the kind words @Queatz, am on the moon after reading your feedback ahaha.
So we then do stand a chance of making a mark on the drivefor*nix frontier.
Sure one day, in the next 8 months or so I plan on dropping by SF, we'll link up and grab the drank -- much appreciated. Otherwise, instead of making me rich, if you'd like you can put that cash towards getting a drive website up or if you have time, just help me take a look around. My UI design skills are terrible but I'd like something to communicate better with users as well as a nice portal/landing page.

Also, I'll be pushing up a change shortly that will allow for exponential back off say when you get timeouts and errors, it will be able to do a best try and this should ensure that you won't have to worry about missing data.

Thanks again :)

**Comment by Queatz** [comment]
Totally, I am a UI master!  I'm actually transitioning to a new job doing web frontend soon and have a week off in between, I might be able to take a stab at that.  Relating to the exponential backoff, it would be cool if after the push finishes if it asked to or automatically retried all the ones that failed (skipping the step where it has to re-index what needs to be synced which sometimes takes 5 mins on my massive dirs lol, the most common errors I was seeing were related to running drive on like 5 different folders causing dns lookup timeouts haha.)  Dude totally hit me up when you come to SF, I'll show you all the good stuff!

**Comment by odeke-em** [comment]
That's awesome, great to get in touch with someone with your skills #Taken1-3  
Ah I see, hope the job transition is going great!
 For sure you can find some starting work at github.com/odeke-em/drive-pages and you can go ham at it.

So in relation to the exponential backoff, actually with it, it will automatically check if it failed to upload, then try again in 1s+ random ms, then in 2s + random ms, then in 4s + random ms, 8s + random ms, until (1^n + random ms) where n is the max number of tries, then give up (you can see the code here https://github.com/odeke-em/exponential-backoff/blob/master/exponential-backoff.go#L42). So it will skip that step of re-indexing until it has to. Also the lookup timeouts should now be solved, if they persist please let me know :)

Now I agree the re-indexing is trippy right now because BoltDB locks the DB file until it has finished using it. I noticed yesterday evening that using two instances of drive on the same account will cause the last started instance to freeze until the first relinquishes control. I will be changing this, as it was behaviour introduced last week from a PR to cut out the problems with waiting on that lockfile. I'll be pushing up a PR introducing batch indexing.
Btw the exponential backoff is already in, I introduced it last night before I went to bed with commit https://github.com/odeke-em/drive/commit/4284e25698f306eafd2e6eb9c9c3d763dc897acb.

Dope, that sounds like a plan, I'll definitely hit you up when in SF, thanks for the offer.

**Comment by Queatz** [comment]
Sweetness, I will be pulling the latest.  Yeah I noticed that it was locking if I tried to run two instances on different folders.  Overall it's feeling really really solid though, the farthest I got with other clients was 4gb, `drive` just topped out 100gb of 220gb total so far :D

**Comment by odeke-em** [comment]
Cool, that's awesome to hear. Current mood after hearing of that news  https://googledrive.com/host/0Bwu8laYc9RTPTHJZMFFxZm5rZFE #alsopoweredbydrive.

**Comment by Queatz** [comment]
Haha that's right bro :smile:

**Comment by odeke-em** [comment]
Hey @Queatz, could you get the last from master and try again, realized I misplaced one of the params so exponential backoff was broken for a bit, I just fixed it with commit https://github.com/odeke-em/drive/commit/cded030fd57598f0ea4b726bbb22735579d4853b and should even be informed when drive is retrying.

**Comment by Queatz** [comment]
Sweet running it now.

**Comment by Queatz** [comment]
@odeke-em what do think about something like this?

http://marinamelodrama.com/drive

**Comment by odeke-em** [comment]
@Queatz this is awesome thank you! It is pretty nice, I like it. Let's move this to https://github.com/odeke-em/drive/issues/274 and then we can talk about a PR or so. I'll ping you with commit access to https://github.com/odeke-em/drive-pages to which we can deploy the webpages to continuously, then periodically make PRs to mother ship here. Thank you again :)

**Comment by Queatz** [comment]
@odeke-em sweet, pushed it there, we can go from there. :+1:

**Comment by odeke-em** [comment]
Thank you @Queatz, I'll also ping @shaggytwodope who did some work too to get drive-pages setup as well as made the logo.
