### ISSUE TITLE
Error 403: User rate limit exceeded, userRateLimitExceeded

### ISSUE THREAD

**Issue by ob7** [odeke-em/drive#343]
Does this error have to do with upload speed or available drive space?

**Comment by ob7** [comment]
and how do I overcome it?

**Comment by odeke-em** [comment]
Hello again @ob7.

Well see the thing is to ensure fair access for all users, you have a limit of queries per second. This quota limit is configured on Google Drive and then regulated by the application from 1qps to max 10qps.
However, this like we had discussed yesterday isn't an error you should be worried about since drive will try to handle it for you with an exponential backoff mechanism. The only reason you see the error is because `Verbose` is set.

**Comment by odeke-em** [comment]
Closing this issue since it is already addressed. Please see PRs https://github.com/odeke-em/drive/pull/321and https://github.com/odeke-em/drive/pull/327
