### ISSUE TITLE
Name clashes on google docs

### ISSUE THREAD

**Issue by mwisnicki** [odeke-em/drive#347]
I get clashes between google documents and folders of the same name but since document will be always converted to some format with different extension, I don't think this should be treated as clash.

In other words, drive should detect clashes between target filenames (after conversion) instead of source filenames.

**Comment by odeke-em** [comment]
Hello @mwisnicki. Welcome to drive and thank you for reporting this.

So, your Google Docs actually get touched locally and not just exported. Exporting can be to different formats but for consistency, an empty file is touched. Your file system won't be able to handle this clash.

Please let me know what you think.

**Comment by mwisnicki** [comment]
As mentioned in #350 the behavior I would prefer is to automatically perform local-only renames and remember the mapping for future syncs.

**Comment by gitnito** [comment]
As I commented in #107:
Since most of these clashes happen when you have a Google document of the same name as a regular file (like .txt, .pdf, etc.), why not handle it like the way the Windows gdrive client does? It basically saves the Google doc file on the local filesystem as "filename.gdoc". Google docs files are easy to detect anywa, since they are just links to a URL. In fact, it is precisely the fact they are just links that these clashes happen. For example, lets say you have a gdoc with very important data, that you want to have access to when you are offline. One way I deal with this is by saving a PDF version of it in the same folder as the gdoc, so that I can read the PDF from my local drive when offline. This will cause a name clash. The solution is not perfect, since you may have two non-gdoc files in drive with the same name, but I bet it will solve 99% of the cases.

**Comment by odeke-em** [comment]
Hello @gitnito welcome to drive since this is our first interaction.

Actually I think that is subjective, I have found it to be that Google Docs with the exact same names clash most of the time. I've found this by observing drives of friends, family most people get onto the UI and make like 5 Google Docs all titled `Tasks` or some generic name. Also, seems like a 99% but with more bugs introduced plus what happens when you have Google Docs with the exact same name, like I've mentioned previously?
However, you are onto something -- I like the simplicity mentioned since we can always  detect Google Docs + Sheets. If you'd like to work on this more, please go ahead or let me know and we can work on it together.

Also like I've mentioned in previous issues I think it spinning up a simple filesystem that maps UUIDs to files might cut the deal without scrambling too much. The mapping would be to mimic what Google Drive remotely does, instead of filepath to file like our native filesystesm do -- however this is just a thought.

**Comment by gitnito** [comment]
A simple solution that would work an pretty much all cases would be to compose the local filename from the original filename plus certain amount (4-5?) of characters from the UUID or hash added at the end whenever there are name clashes.

**Comment by odeke-em** [comment]
Btw @mwisnicki, as I previously mentioned, name clashes could happen on type of file, not just  Google Docs -- you just happen to have duplicated Google Docs. Coming to think of it, this isn't really an issue related to drive before same name, different file handling is in. This is a subset of https://github.com/odeke-em/drive/issues/156

**Comment by odeke-em** [comment]
Ping!

**Comment by odeke-em** [comment]
Closing this issue in favor of #156
