### ISSUE TITLE
Specify destination path for push

### ISSUE THREAD

**Issue by melat0nin** [odeke-em/drive#35]
Hello

I've looked through the docs and command line options but I can't see where to specify the destination path. I'd like to backup some folders from the local machine but I don't want them in the root of my Google Drive. Am running 0.0.4.

Many thanks!

**Comment by odeke-em** [comment]
Hello @melat0nin, too bad that you couldn't find the documentation.
To push you have a couple of options:
1) Create a directory within the drive directory of your local machine, add content to it then push it
2) Create a directory within the drive directory of your local machine, then mount content to it ie without having to explicitly copy it first into the dir.
To perform option 1
   $ cd ~/google_drive
   $ mkdir content
   $ cp -R $SRC1 $SRC2 $SRC3 content
   $ drive push content

To perform option 2, make sure that the mount point already exists on the drive
  $ cd ~/google_drive
  $ mkdir content
  $ drive push content // Don't forget this step
  $ drive push -m /media/SDCARD ~/Desktop/backups ~/Desktop/images content

Please look at the README it shows how to use the different commands and usage.
Let me know if this helps.

**Comment by melat0nin** [comment]
Thanks for the explanation @odeke-em, it makes sense :) I think I just didn't fully understand the concept of mirroring the desired structure locally before uploading, rather than choosing where to upload to, if you know what I mean.

**Comment by odeke-em** [comment]
@melat0nin no worries am glad to be of help. Btw, would you mind sending me(or posting it on issue #22 ) that crash report that you have provided earlier on? Thanks.

**Comment by davidv171** [comment]
I'm probably not using the program correctly, but I'm still gonna ask because I still havent figured it out.

I have initialized drive in ~/Pictures . What I want to do is push ~/Pictures/Screenshots to a Google drive folder Screenshots/ . The drive folder is not deeply nested, it'd go like this: root/Screenshots/

What I've tried:

cd ~/Pictures && drive push Screenshots/ 

This just doesnt stop "Resolving" 

Using cd ~/Pictures && drive push Screenshots/*  just copies it into root. What am I missing. Am I supposed to be making new directories after initializing?
