### ISSUE TITLE
Better drive 'push' folder matching (specifically on unreliable connections)

### ISSUE THREAD

**Issue by raintonr** [odeke-em/drive#353]
When recursively pushing files up to drive (folders with sub-folders) I have noticed that on a poor connection sometimes a folder that already exists on drive is not detected.

This leads to a new folder with the exact same name being created (which is completely possible in drive) and all the files in the source folder being re-sent (even if some of them already exist in the drive folder which was not detected).

I have only seen this behaviour on slow connections but better detection of this scenario is required, because once two folders with the same name exist on drive things get very messy.

**Comment by odeke-em** [comment]
Hello again @raintonr, thank you for reporting this issue.

For starters, what version of drive have you been running? I suspect you are on older versions for which this was a problem. This is because I last interacted with you about 5 months ago in March when this was still a problem. This issue was fixed a few weeks ago and you could get the latest by
```shell
$ go get  -u github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by raintonr** [comment]
Thanks for the tip. Yes, I was on 0.1.4. Just updated to 0.2.8.

**Comment by odeke-em** [comment]
Cheers!
