### ISSUE TITLE
Question: Uploading multiple accounts using drive

### ISSUE THREAD

**Issue by rjnagal** [odeke-em/drive#362]
Hi,

 I am trying to migrate data for a set of users from a filer to google drive. The drive accounts are from a shiny new google apps account and are completely empty. I was wondering a wrapper over drive would be a good tool to use for this case. I am hoping to use admin access to push the files to user accounts. I also want to run a delta migration later using cksum or size+modtime.

 Looking for opinions on whether this is a terrible idea, or someone has done it successfully using drive before. I am looking to use drive as a starting point and can tweak it to fit anything that it might not do yet.  But looking for a quick  yay/nay before starting. Thanks!

**Comment by odeke-em** [comment]
Hello @rjnagal. Thank you for reporting this and welcome to drive!

So, the only thing that ties your files to an account/credentials is the .gd directory in the top level directory.
This translates to only being able to upload files that you have disk/"physical" access [1] to.
 If you wanted to switch out accounts you could `drive deinit` that account's root directory then `drive init` with another account, and then push say with no-clobber.
So let's say we have the filer on disk, for every account we'd like to authorize you'll just follow the common run through init, push, deinit and iterate. Here is a sample simple bash script to achieve this:

```shell
$ cd ~/filer
$ # For each account on the next prompt
$ cat << ! >> multiInit.sh && chmod +x multiInit.sh
> #!/bin/bash
> while [ 1 ]
> do
>   echo -e '\a' # For simplicity just toggle the ascii bell. You could even go fancy and say `spd-say "next account"` on Ubuntu or whatever the equivalent is on your OS.
>   drive init && drive push --exclude-ops "delete" || (echo "Failed to init & push" && break)
>   (yes | drive deinit) || (echo "Failed to deinit this account" && break)
> done
> !
$ ./multiInit.sh
```
In the script above, please note the `--exclude-ops` option to exclude deletions. I've found that first time users might be appalled when drive tries to match up contents of the source by deletion. Later on, they find out this is intended behaviour. Also in case you trash anything remotely you can always untrash it

In regards to delta migration, I haven't yet finished the delta uploads. I do have the different components but we'll still have to piece together the resumable + multipart uploads first, then the rest will be easy. I haven't had much time to put them all together, but I have written all the pieces that we'll need to get this in.
But otherwise I think you should be able to migrate these accounts in. Please don't hesitate to ask any questions or provide ideas.

**Comment by rjnagal** [comment]
Thanks for the details @odeke-em 
I think I got it working.

The only code changes I made was to change init to process a service account with drive api auth so I don't have to feed oauth consent for every user.

For my setup:
. I mounted the /filer as read-only
. Created a /migrate and added a directory for each user
. Linked off each user's top-level folder under /migrate/user
. Used multiInit.sh to init and push each directory, but skipped deinit (thanks for the tip on --exclude-ops. That makes me feel much better)

I tried making some changes to original files in /filer and ran a push for all users again. It did the right thing and uploaded only modified and newly added files. I am assuming that if I didn't do a deinit, i'll be able to do a "modified + newly added" push anytime.

Did I miss something, or is that it? I didn't expect to be done in a couple of hours :) Will run some more tests in the morning.

Thanks again, this is an amazing tool! :heart: :heart:

**Comment by odeke-em** [comment]
@rjnagal awesome!! Thank you for the kind words.

Am glad to know you were able to get this started. Yes in deed, if you don't do a deinit the account will still be authorized to run from that root directory.
I don't think you missed something. A fast internet connection and multi core CPU should get things running really fast. Cool to know that the upload went fast for you :)

**Comment by rjnagal** [comment]
Migrated 200+ accounts from a netapp filer to Drive. Worked without a hitch.
I might clean up my changes and send a PR for using service accounts for auth.

Other than that, all done here. Closing.

**Comment by odeke-em** [comment]
Cool!! That's awesome, great news to hear. For sure, a PR for service accounts would be awesome. Thanks.

**Comment by MaxBer** [comment]
Hi, @rjnagal would you mind sharing the code changes to init for authenticating with service account keys?

Thanks in advance! Also thanks to @odeke-em for maintaining drive!

**Comment by georgewf** [comment]
Hi, I was wondering about this too. Set up a service account but can't figure out how to use it. On a whim I tried using the GOOGLE_API_CLIENT_ID and GOOGLE_API_CLIENT_SECRET environment variables and got the following reply:

Error: redirect_uri_mismatch

The redirect URI in the request, urn:ietf:wg:oauth:2.0:oob, can only be used by a Client ID for native application. It is not allowed for the &#39;WEB&#39; client type. You can create a Client ID for native application at https://console.developers.google.com/apis/credentials/oauthclient
