### ISSUE TITLE
pulling changes without a symlink deletes symlink target

### ISSUE THREAD

**Issue by dvera** [odeke-em/drive#370]
On my system, I created a symlink in my gd dir to a file outside this dir. When I pulled changes from drive that did not have this symlink, the TARGET of the symlink got deleted, but not the symlink itself.

Is this expected behavior?

**Comment by odeke-em** [comment]
Hello @dvera, thanks for reporting this and welcome to drive!

Sorry for the late reply, one of those long school days :)

This is expected behaviour since symlink full path resolution is done. Please see https://github.com/odeke-em/drive/issues/80 and also the README file

<img width="805" alt="screen shot 2015-09-08 at 10 58 27 pm" src="https://cloud.githubusercontent.com/assets/4898263/9753654/2bde6c74-567d-11e5-9c7d-940991d867d7.png">

**Comment by odeke-em** [comment]
Ping!
