### ISSUE TITLE
i/o timeout downloads empty file

### ISSUE THREAD

**Issue by matthewlenz** [odeke-em/drive#371]
If 'drive pull' can't connect to certain google servers (for whatever reason) it will download an empty file.  I didn't test it but I'll bet if you then do a 'drive push' (later once you do have connectivity) it will nuke the file(s) on google drive as well.

$ drive pull -no-prompt=true
Resolving...
0 / 198486 [-----------------------------------------------------------------------------------------------------------------------------------] 0.00 % pull: /Backup--Customer_Restore_Guide-UNIX.pdf err: Get https://googledrive.com/host/XXXXXXXXXXXXXXXX: dial tcp 216.58.216.97:443: i/o timeout
0 / 198486 [--------------------------------------------------------------------------------------------------------------------------------] 0.00 % 15s
$ ls -l
total 0
-rw-r--r-- 1 XXXX XXXX 0 Sep  8 08:46 Backup--Customer_Restore_Guide-UNIX.pdf

**Comment by matthewlenz** [comment]
v0.2.9, btw.

**Comment by odeke-em** [comment]
Hello @matthewlenz! Thank you for reporting this issue and welcome to drive!
My apologies for the late reply, long school day :)

So that's an interesting case that I like, and I think I have a way of ensuring this can work well. Basically, for every download, create a temp file that can be cleaned up if failed, else renamed to the target file hence a "rollback". Now for starters before this is in, there are ways of preventing nuking of your files
`--exclude-ops` delete or `--no-clobber`. Even after trashing files upstream, you can untrash them.

**Comment by odeke-em** [comment]
Hello @matthewlenz . Please get the latest from master, I once encountered this error and was able to reliably reproduce so it was my test case when writing PR https://github.com/odeke-em/drive/pull/395. If the number of retries is exhausted, then it will fail and you'll have to re run it.
Please re-open if it persists and thank you for reporting this issue and for your patience.
