### ISSUE TITLE
Bolt: maxMapSize and maxAllocSize issue

### ISSUE THREAD

**Issue by sorentorp** [odeke-em/drive#373]
Hi, any of you have any ideas here?

Running Go vers. 1.3.3

go get -u github.com/odeke-em/drive/drive-gen && drive-gen
github.com/boltdb/bolt
../../gopath/src/github.com/boltdb/bolt/bolt_arm64.go:4: maxMapSize redeclared in this block
	previous declaration at ../../gopath/src/github.com/boltdb/bolt/bolt_amd64.go:4
../../gopath/src/github.com/boltdb/bolt/bolt_arm64.go:7: maxAllocSize redeclared in this block
	previous declaration at ../../gopath/src/github.com/boltdb/bolt/bolt_amd64.go:7

**Comment by pcoughlin** [comment]
What does this have to do with IRremote?

Please be specific about how you are using IRremote and it would be good if you provided a sample of your sketch.

**Comment by odeke-em** [comment]
Hello @sorentorp, welcome to drive and thank you for reporting this issue.

I haven't encountered this issue before, but it was an issue reported to boltDB at https://github.com/boltdb/bolt/issues/416. Seems like it was fixed with https://github.com/boltdb/bolt/pull/418. Please try again.

@pcoughlin haha, did you mean to comment on another repo?

**Comment by sorentorp** [comment]
Thank you so much... Their fix worked ;-)
