### ISSUE TITLE
Force filename when doing pull

### ISSUE THREAD

**Issue by ampkeegan** [odeke-em/drive#388]
I'm working on a project where I need to pull down one file, parse it to get the links to all other files within it, then pull them, get their links, download, etc etc. 

This would be much easier if I could specify the output filename when doing a drive pull. Maybe I'm missing it but I don't see a way to do it.

Ideally, it would work something like this:

 #drive pull -no-prompt -export html -filename doc_id_here --id doc_id_here

Thanks!

**Comment by odeke-em** [comment]
Hello @ampkeegan, thank you for reporting this issue and welcome to drive!

Firstly sorry for the late reply, these class assignments kept me away :)

In regards to you issue: sure the case could work for a plain pull and that could be a feature request. However, that won't work for `--export` because export creates an _export suffixed directory of exports since the export list could be quite large, and the files will themselves be suffixed by their extension so the --filename purpose no longer serves.

Also you can pass in the `--export-dir`.
Another thing is that potential cluttering your local might cause spurious changes for the exported files.

Otherwise for the ordinary case, creating an out filename is a good case. However before exploring that case, I just wanted to let you know that for items that can be "pulled" e.g non Google Docs and Sheets,
you can pull their content piped e.g
```shell
$ # drive pull --piped <filename> | <a_filter>
$ drive pull --piped | grep -i moon | wc -l
```

As a quick hack to try to put myself in your shoes:
```shell
$ cat << ! >> crawler.sh && chmod +x crawler.sh
> #!bin/bash
> function crawler() {
>    # Assuming you've defined processContentToLinks and it can read from stdin
>    # We'll traverse every link spewed back from processContentToLinks
>     drive pull --piped "$1" | processContentToLinks | while read F;do crawler "$F";done;
> }
>
> for i in "$@"
> do
>    crawler "$i"
> done
> !
``` 

Now let's start that crawling
```shell
$ ./crawler.sh info/text mylinks/2015/unexplored
```

**Comment by ampkeegan** [comment]
Thanks for the response. The piped option is a great solution in some cases. In my particular scenario I'm only looking for drive documents. My workaround is to export the filename to a folder with the Id in the folder name, then look for any html file that exists in that folder. 

My solution works for my needs now, but future users might benefit from forcing the output filename.

Thanks!

**Comment by odeke-em** [comment]
Hey @ampkeegan, as explained above, forcing the output filename isn't feasible currently because multiple paths are pulled/handled in almost every operation on drive. In my opinion, working to account for that one case introduces unnecessary complexity. If you'd like, please feel free to submit a PR otherwise.

**Comment by odeke-em** [comment]
Am gonna mark this as won't fix since it doesn't apply for drive's usage patterns since multiple paths are implied implicitly and mostly used on a pull or push. Adding an option to force a filename will be unnecessary complexity for a small case as explained before.
You can do this.
```shell
$ drive pull --piped your_file > outfile
```
