### ISSUE TITLE
Pushing pulled google docs

### ISSUE THREAD

**Issue by AndreyZykov** [odeke-em/drive#400]
Hello!

I want to create some sort of backup for my google drive shares using drive utility. Now I'm testing  functionality for restoring my data and stuck with following problem:

I have google docs (spreadsheets, etc.) which was pulled on my local drive. 
Now let assume that some file was accidentally deleted. I want to restore it from local copy and run drive push. Deleted Google Docs file gets back BUT it can't be open now - Google Drive reports a warning "Whoops! There was a problem previewing this document" and offers to open it in different apps. If I select to use Google Docs app to open it - the document opens but it blank, only name of files is the same.

Also, I noticed, that it could be because of mime type
Source file had:
MimeType                  application/vnd.google-apps.document
File on my local drive have:
inode/x-empty
Restored file becomes:
MimeType                  text/plain

Any help?

**Comment by odeke-em** [comment]
Hello there @AndreyZykov thank you for reporting thi issue and welcome to drive!
So fo starters, I just wanted to let you know that drive supports untrashing ` drive untrash -h`, `drive list --trashed`. Another thing to notice is that Google docs + sheets cannot be pulled raw but exported. In fact what happens is that depending on where you are on Linux or not you are on Linux a *.desktop file is created, otherwise an empty file for consistency is created locally. That information is mentioned in the README e.g https://github.com/odeke-em/drive#desktopentry 
Please let me know what you find.

**Comment by AndreyZykov** [comment]
Thanks!
I'll test your suggestions.
But what about my exact test case - is it designed so? I mean if I want to push back google docs file which is absent target folder and it becomes corrupt.

**Comment by odeke-em** [comment]
Your case will fail because local files are just empty, and previously mentioned they cannot be pulled raw. The way to restore Google Docs is by untrashing them.

**Comment by AndreyZykov** [comment]
I see, thank you!

**Comment by AndreyZykov** [comment]
One more question :)
Is it possible to create exported files instead of original google docs file when running drive pull?
i.e. I have file named "test" (google doc) and run:
$ drive pull -export docx
and get new folder "/test_exports" and file /test_exports/test.docx within...
But it would be good just to get file "test.docx"

**Comment by odeke-em** [comment]
Good question and observation. It does seem more convenient the way you suggested. So the common case is a user exporting like pdf,txt and more than one format. The better part though is that adding the files to an exported directory enables you to avoid cluttering your drive since if the export is made to "." you'll have a new file that you have to push. You could decide to skip adding that file, but do that for 6 exportable files and you'll have trouble ignoring them. Since drive supports a .driveignore file, you can just ignore `_exports` and voila you won't have to worry about spurious additions and deletions.

**Comment by odeke-em** [comment]
Ping!

**Comment by AndreyZykov** [comment]
Hey! 
I've solved my issues with a tiny script which is remove useless google docs links and moving exported files from subdirs to original directories.
The only issue i haven't fixed yet - how to backup file from other cloud apps like draw.io
Cause they also storing as a link and can't be exported

**Comment by dman61** [comment]
I was able to duplicate this issue. If I do:

/usr/bin/drive push -no-clobber  -verbose -no-prompt myfile 

The file uploaded will be 0 bytes. Drive list also shows them as nil. 
It appears to have something to do with the -no-clobber flag. If I remove that flag then the files upload fine.
