### ISSUE TITLE
Pulling Googlecentric Files

### ISSUE THREAD

**Issue by viruscmd** [odeke-em/drive#404]
I Might be doing something wrong but is there away to pull gdocs, and gsheets? When I pull the down they come as two separate files, "Foo" & "Foo.desktop", but not "Foo.gdoc".

Any help would be greatly appreciated!

Regards,
Austin

**Comment by odeke-em** [comment]
Hello again @viruscmd! Thanks for reporting this.

So Google Docs + Sheets cannot be downloaded raw but only exported. The files that get downloaded are an empty file for consistency and a .desktop file if you are on Linux -- .desktop file is clickable. 
In order to export such a file, you'll need to pass in flag "--export <exportTypes>" eg "drive pull --export pdf,docs,txt 2013Docs"
The README actually talks about this https://github.com/odeke-em/drive#exporting-docs.

Please let me know if this works for you.

**Comment by viruscmd** [comment]
@odeke-em  Thanks for the info. I just want to clarify that if I use --export xlsx,docx it will export the all gsheets as xlsx, and gdocs as docx? i.e.
    folder foo has two files, bar.gsheet and baz.gdocs. Using ''--export  xlsx,docx" the pulled files will be "/_exports/bar.xlsx" & "/_exports/baz.docx".

Thanks,
Austin

**Comment by odeke-em** [comment]
Yes in deed. If it finds xlsx exportable, it will export to xlsx if it finds docx exportable it will export to that.

**Comment by viruscmd** [comment]
@odeke-em You are the best! Thanks.

**Comment by odeke-em** [comment]
Thanks for the kind words @viruscmd :) and for reaching out!
