### ISSUE TITLE
[feature] editing of file description field

### ISSUE THREAD

**Issue by marcoblancas** [odeke-em/drive#414]
Related with #412... I don't know if there is some way to set the description filed for pushed files. May be this is a new feature.

**Comment by odeke-em** [comment]
Hello again @marcoblancas!
So it is going to be an awkward one for pushing files since multiple files can be pushed. However, a separate command for already uploaded files can do, just like the WebUI does. Otherwise it is a great feature request. I'll have some time over the weekend to get this in, or if you'd like please feel free to spin up a PR and I can walk you through it :)

**Comment by marcoblancas** [comment]
Thank you very much @odeke-em . I would love to be able to program this feature but I don't know nothing about "go". I hardly was able to compile the new version to test the results.

I'm new on drive this week... congratulations... this is a very useful tool.

**Comment by odeke-em** [comment]
Awesome, thank you am glad to know drive is useful for you. No biggie, I'll get started on it when I have some time and if you wouldn't mind, I'll ping you and ask for your feedback!

**Comment by odeke-em** [comment]
Addressed by PR https://github.com/odeke-em/drive/pull/423. Please get the latest from master.
Thank you for requesting for this feature!
