### ISSUE TITLE
Starred Files

### ISSUE THREAD

**Issue by ManuCart** [odeke-em/drive#431]
Hello,
What's the command to download only the starred files?

**Comment by odeke-em** [comment]
Hello @ManuCart thanks for reporting this and welcome to drive!

Unfortunately the command to download only starred files hasn't yet been implemented, but it can be added.

**Comment by odeke-em** [comment]
Please feel free if you'd like to contribute a PR as this week is kinda tricky for me with assignments and midterms but probably at the end of the week, if a PR hasn't been made.

**Comment by ManuCart** [comment]
Ok thanks for your answer. I'll be wait for this feature.

**Comment by ManuCart** [comment]
Oh,it's too bad for waiting v0.3.3, I really need this function

**Comment by odeke-em** [comment]
Oh my bad, I didn't realize this was much needed. The reason I've pushed this to the next release is because starred files appear to be in the root but actually need to have a reverse lookup for all their parents till we get back to the root. I had actually started working on this using a remote machine two weeks but had to run for a class then forgot about it, after logging off. I wish this had crossed my mind last night when I was whipping out drive code. So how about this, I get a week's break off from school starting on Friday 6th November 2015 and I make a promise to get it in as soon as am free :)

**Comment by ManuCart** [comment]
Thanks very much, I know you give your best.

**Comment by odeke-em** [comment]
Hello again @ManuCart, 
Thank you very much for the patience. I've implemented this functionality in PR https://github.com/odeke-em/drive/pull/467. Please get the latest from master and let me know how it goes.
Cheers!

**Comment by odeke-em** [comment]
@ManuCart as a bonus I've added the ability to "star" or "unstar" files in PR https://github.com/odeke-em/drive/pull/470, also present in master.

**Comment by ManuCart** [comment]
Hello,
Wonderful job, but the pull request with --starred arg still working only on the root folder

**Comment by odeke-em** [comment]
Ah I see, yes it is relative to the current working directory like the other commands which is what I meant before by it being an awkward command because files appear in root but are in different places. The alternative would be for me to add an option '--all' that will be directory agnostic but will only be run from master. Unfortunately am away from home or a physical computer for the next 7 hours but will do so when I get home. Thanks

**Comment by odeke-em** [comment]
Hello @ManuCart, please get the latest from master PR https://github.com/odeke-em/drive/pull/476 adds the ability to pull all the starred files (it is working directory agnostic), so this is a bonus feature as well as allowing for pulling starred files by matches and also relative to the current working directory.
Thanks again.

**Comment by ManuCart** [comment]
Thanks for all, it's working that I expected. Your script help me a lot.
Great job.

**Comment by odeke-em** [comment]
Thank you very much for the patience, for raising this issue and for the kind words. Am glad to know that it has been addressed for you. Cheers!

**Comment by ManuCart** [comment]
I found a bug and it's a problem for me.
When a starred file is in trash and not empty trash
I do a request about starred files, the starred trash files are comming with the starred files.
Could you help me?

**Comment by odeke-em** [comment]
Could you open a separate issue and close this one, that's a broad scope for a feature request. That's a bug that can be fixed on its own. Thanks.

**Comment by ManuCart** [comment]
OK thanks
