### ISSUE TITLE
Should "drive rename" also rename the local file/directory?

### ISSUE THREAD

**Issue by smblott-github** [odeke-em/drive#459]
$ drive pull foo
    $ drive rename foo bar
    $ ls
    foo

That's pretty weird.

Might it be better to rename the local file/directory too, if present?

A *bad* use case would be if there's a local file/directory which just happens to have the same name.  So perhaps such a feature would have to be optional:

    drive rename -rename-local=true foo bar

**Comment by odeke-em** [comment]
Yap I agree, the only problem though is that you can't rollback locally and a lot of information has to be compared to make sure local and remote match up. I originally was going to implement it so that it works both ways but hesitated for a couple of reasons one of them being what you mentioned a local clash, not being able to rollback etc. I agree we could have an optional mode. BTW the exact same thing applies for move, delete, copy, new.

**Comment by smblott-github** [comment]
An alternative would be to have a shell wrapper; e.g., here's a quick hack:

    #!/usr/bin/zsh
    
    if command $0 $argv && (( 0 < $#argv ))
    then
       local cmnd=$argv[1]
       shift
       while (( 0 < $#argv )) && [[ $argv[1] == -* ]]
       do
          shift
       done
       case $cmnd in
          'rename' ) mv -v $argv  ;;
          'move'   ) mv -v $argv  ;;
          'mv'     ) mv -v $argv  ;;
    
          'delete' ) rm -rv $argv ;;
          'rm'     ) rm -rv $argv ;;
    
          'copy'   ) cp -rv $argv ;;
          'cp'     ) cp -rv $argv ;;
       esac
    fi

**Comment by odeke-em** [comment]
Good one :+1:

**Comment by odeke-em** [comment]
Hello @smblott-github, thank you for the patience. I got sometime finally tonight and implemented this with https://github.com/odeke-em/drive/pull/632. Please get the latest.
