### ISSUE TITLE
cron job

### ISSUE THREAD

**Issue by cjudilla** [odeke-em/drive#48]
Hi,

We created a php script with an exec function to execute the drive client in a distinct way and then added the php script to cron. However we are getting issues in running the drive client in cron. cron uses sh / bash to execute commands and it cannot execute drive.  The error is: cannot execute binary file

I'm not sure on how to go about this issue. Please help.

**Comment by odeke-em** [comment]
For starters were you able to install drive on that machine and be able to run it from the command line like
```shell
$ drive version
```

**Comment by cjudilla** [comment]
Hi,

Yes. That's the weird thing about it. I can run drive in the command line, I can also run the php script with the 'exec' function that (executes drive ) in the command line as well w/ no problems. When I run it cron, there's a process (/bin/sh -c myphpscript.php) that runs and fills up the logs and disk space. Thanks for the help.

**Comment by CountryBumkin** [comment]
This is a very common problem with cron and it's due to the different environment configuration.
I have had more success with the 'at' command, this provides an environment the same as your terminal window.
For example this script resubmits itself each day at 13:00 hrs and puts the messages and errors in a log file for checking.
#!/bin/sh -x
exec > /home/zzz/edev/drive/Gdrive.log                                                                      
exec 2>&1
at 1300 -f /home/zzz/edev/drive/Gdrive.sh
#
date
drive push -r -no-prompt -no-clobber /home/zzz/Gdata
date
exit

You may need to install the 'at' command from your repo. Command details here
http://www.computerhope.com/unix/uat.htm

**Comment by cjudilla** [comment]
Hi CountryBumkin, odeke-em,

Thanks for your prompt replies.

I'll use 'at' as an alternate solution in the future. We were able to get it to work by creating a symbolic link linked to the drive binaries in the /bin directory. This is quite odd as we already added the drive bin directory to the $PATH env variable. Anyway, hope that this will help others in setting up drive in cron.

**Comment by odeke-em** [comment]
Thanks @CountryBumkin for helping to resolve this. @cjudilla glad you've been able to resolve it.
