### ISSUE TITLE
Can this sync a folder structure?

### ISSUE THREAD

**Issue by webstone-ro** [odeke-em/drive#530]
I'm sure I didn't carefully go over all the docs, but if I only wanted to push to Drive new folders/files, would that work?
I'm using Python on Raspbian, but my perfect setup is pretty simple:
- capture stills from camera that go into local_images/YYY-MM-DD type folders that are automatically created - DONE
- upload only new folders/files to GDrive (create the remote_images/YYY-MM-DD folders if they don't exist remotely)
- delete 10-day old folders locally
- delete 30-day old folder remotely

I get the feeling drive would be perfect for this, together with cron. Could someone point me in the right direction, or is this the wrong place to ask?
Thanks

**Comment by canpolat** [comment]
Yes, you can achieve this using drive. I assume `local_images` folder already exist and all other folders under that is auto-generated.

In your browser, create a folder in Google Drive (PiCaptures). Then get the ID of that folder from the URL (`PiCapturesID`) (how to get folder ID: http://stackoverflow.com/a/13664848).

In your RPi, create a folder (gdrive). Navigate into gdrive folder and pull the newly created empty remote folder (replace `PiCapturesID` with the actual ID):

    cd gdrive
    drive pull --id PiCapturesID

This will create a new folder named PiCaptures (or whatever you have called your folder in Google Drive). It will be empty.

Now, you can direct your script to create your folders in this PiCaptures folder (they will look like `gdrive/PiCaptures/YYY-MM-DD`).

After this setup is in place, manually copy some folders in the `gdrive/PiCaptures` folder. Navigate to the PiCaptures folder and perform a `push`:

    cd PiCaptures
    drive push

If you want to automate this you should consider using the `quiet` flag with push so that it doesn't prompt the user for input.

I hope this helps.

**Comment by odeke-em** [comment]
@canpolat you the real MVP, thanks!!
I just wanted to add that with drive you can create new folders without having to use the browser :)
```shell
$ drive new --folder a1 PiCaptures
```
and it is documented here https://github.com/odeke-em/drive#new-file.

Thanks!

**Comment by odeke-em** [comment]
Also there is https://github.com/pageauc/pi-timolo by @pageauc which also uses drive.

**Comment by webstone-ro** [comment]
That was super-helpful and I got it working quickly. I guess for me the confusion was that I thought it would go something like: drive push local_folder to remote_folder
or something along those lines. But this works perfectly. I am writing my own python code now for motion detection but, yes, pi-timolo and the included gdrive was where I first got my inspiration.
Thanks again

**Comment by pageauc** [comment]
Please Note that I have updated my Raspberry Pi pi-timolo program https://github.com/pageauc/pi-timolo with latest 0.3.8.1 version of drive_armv6.  It will be installed as gdrive and gets copied to /usr/local/bin.  
There is a new version 1.9 of sync.sh with better error checking. See code for details here https://github.com/pageauc/pi-timolo/blob/master/source/sync.sh and Wiki here https://github.com/pageauc/pi-timolo/wiki/How-to-Setup-pi-timolo-gdrive-sync
and here https://github.com/pageauc/pi-timolo/wiki/Instructions-to-Re-Purpose-sync.sh
Regards
Claude ....
