### ISSUE TITLE
Install fails on debian

### ISSUE THREAD

**Issue by mgillespie** [odeke-em/drive#555]
root@RPI:~# go version
go version go1.3.3 linux/arm
root@RPI:~# go get -u github.com/odeke-em/drive/drive-google
# github.com/odeke-em/drive/src
24: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
root@RPI:~#

Have no idea what this all means, other that the install didn't go smoothly at all.

**Comment by mirohe** [comment]
Hello,

I had trouble if I used a version of "go" (golang) less than 1.4.
I am using "go" version 1.4.2 and work ok.

**Comment by odeke-em** [comment]
Hello @mirohe, thanks for this and welcome to drive!
Firstly my apologies for the late replies, I've been so busy with school and work.
If you wouldn't mind, could you create a PR to update the README and say go1.4 and above instead of go1.3? If you can't, no biggie, I can update it then, I just wanted to make sure you get credit for this.
Thanks!

**Comment by odeke-em** [comment]
As mentioned by @mirohe please use >= go1.4.
