### ISSUE TITLE
Drive API limit??

### ISSUE THREAD

**Issue by Chris2048** [odeke-em/drive#565]
Hi, When I try:

google-drive pull --fix-clashes

I get a url returned, which itself returns json:

{
error: {
errors: [
{
domain: "usageLimits",
reason: "dailyLimitExceededUnreg",
message: "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
extendedHelp: "https://code.google.com/apis/console"
}
],
code: 403,
message: "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
}
}

What relationship does drive access have to the dev API??

**Comment by odeke-em** [comment]
Hello @Chris2048 thanks for reporting this issue and welcome to drive!
For starters, please take a look at https://github.com/odeke-em/drive/issues/480.
This is because currently there are default credentials that are used by a whole lot of people, so you could either make an API project and just set your env keys as specified in https://github.com/odeke-em/drive#configuration.
The linked issue is related to a bug on Google Drive's backend too.

**Comment by Chris2048** [comment]
Thanks @odeke-em :-D

Ah, Thanks, I did a similar thing for rClone (drive backend) as per comment [here](http://security.stackexchange.com/questions/107370/should-i-trust-grive2/107372) (by Jonathan Gray) actually. I'll try to do this again, Thanks!

**Comment by odeke-em** [comment]
@Chris2048 sounds like a plan, you can create one by going to Google Developers Console, creating an application and enabling the Google Drive API on it, that should generate for you a clientId and secret then you can set that in your env as documented here https://github.com/odeke-em/drive#configuration. This will ensure that you won't be squeezed out of the client's default credentials that are used by a whole lot of people. However, there is still a bug on Google Drive's backend so please keep your ears to the ground with the issue that I linked.
I'll close this issue since you seem to have resolved it.

**Comment by gauteh** [comment]
Just in case someone else wants to use your own API keys, you can find the wizard to request one here: https://developers.google.com/drive/v3/web/quickstart/go and https://console.developers.google.com/start/api?id=drive (you'll get the client secret key after having created the project, saved it, and re-opened it).
