### ISSUE TITLE
Question: upload a screenshot, share publicly, get url for pasting

### ISSUE THREAD

**Issue by RickCogley** [odeke-em/drive#567]
Hello - I'd like to use drive to upload a screenshot, and I've got it installed and running, as well as having done an init in ``~/gdrive``. I use Mac OS X.

When I take a screenshot, it gets saved as a png file in ~/Screenshots. Something like: ``Screenshot 2016-01-25 14.59.35.png``

OS X lets you set up folder watching, and run a script when a new file is created in some folder. My goal is: when I create a screenshot, I want to trigger a command to upload it to, say, ``Screenshots`` on my Drive, and get the share URL. 

OS X has a ``pbcopy`` command (pasteboard copy) which if you pipe std-out to, will put that on the clipboard. I want to grab the share URL to my clipboard this way, for pasting to various chat apps like HipChat or Flowdock. 

How can I do this? I've tried a number of different command variations, but I must be doing something wrong and somehow missing the point. 

Appreciate any help. Thanks!

**Comment by RickCogley** [comment]
Hello - I figured out how to do this, somewhat. 

* Created a folder in ``~/gdrive`` to match one in my Google Drive, called ``Screenshots``. Switched to is with ``cd``.
* Tried uploading from my screenshots folder, outside this ``gdrive`` folder, but, that does not work. 
* Copied png file into ``gdrive/Screenshots`` and tried uploading from there. This works. 
    * ``$ drive push --quiet test-screenshot.png``
    * ``$ drive edit-desc --description "This is the description for searching." test-screenshot.png``
    * ``$ drive pub test-screenshot.png``
    * ``$ drive url test-screenshot.png | grep -o 'http*.*' | pbcopy``

Questions if you don't mind: 

* Would it be possible to get the ``url`` option to work so it just returns the url, and not the extra text. I can do what I did above, using ``grep -o`` or ``awk`` etc, but it would be better if there were a native solution. 

* Can I string all those commands together in a single command, like ``drive push pub url somefile.png``? Or, is how I did it, one by one, the way? 

* Can I initialize another folder, such as ``~/path/to/my/screenshots``, as being linked to my Google Drive ``/Screenshots`` folder? So that I can continue to create files there, and then run the ``drive`` command directly from there? 

* If I use the method I happened upon, by copying the screenshot file to ``~/gdrive/Screenshots`` and doing the commands, then, after it's uploaded to Google Drive, if I delete it normally (meaning ``rm -rf myscreenshot.png`` etc), will it _also_ be deleted off Google Drive? I think not, but I just want to confirm. 

Please advise, and thanks for a great app.

**Comment by odeke-em** [comment]
Hello @RickCogley, thanks for the question and welcome to drive.

My apologies for the late reply, I've been really busy.
Thank you for the kind words too!

So to answer you questions, there are a few alternatives.
```
Tried uploading from my screenshots folder, outside this gdrive folder, but, that does not work.
```
What you can do is use the mounted push option "--m" that is
```shell
$ cd ~/myDrive #If this is where you performed the init
$ drive push -m ~/Desktop/music ~/Pictures/2014/02 .
```

`
Would it be possible to get the url option to work so it just returns the url, and not the extra text. I can do what I did above, using grep -o or awk etc, but it would be better if there were a native solution.
`
For sure that could be added, the only problem though is if you are publishing many files, how do you differentiate them? However we can just see if it is only one file being processed.

`
Can I string all those commands together in a single command, like drive push pub url somefile.png? Or, is how I did it, one by one, the way?
`
Unfortunately not yet, I'd welcome a PR though :)

`
Can I initialize another folder, such as ~/path/to/my/screenshots, as being linked to my Google Drive /Screenshots folder? So that I can continue to create files there, and then run the drive command directly from there?
`
Yes, drive can work with symlinks. Otherwise just a lone folder outside of the root ie "/" on Google Drive, won't be possible. As long as you have the same credentials in the .gd directory, and then somehow you can keep the same relative structure from "Google Drive" root in there, then you can achieve that.

`
If I use the method I happened upon, by copying the screenshot file to ~/gdrive/Screenshots and doing the commands, then, after it's uploaded to Google Drive, if I delete it normally (meaning rm -rf myscreenshot.png etc), will it also be deleted off Google Drive? I think not, but I just want to confirm.
`
Yes, but only if you've made a explicit push. drive doesn't do auto-sync it is manual.
In the normal mode of pushing that is `drive push paths...`, missing paths will be removed.
However you can:
a) selectively choose what you want pushed up `drive push a/b/c/d e/f/g/h`.
b) use `--exclude-ops` https://github.com/odeke-em/drive#note e.g `drive push --exclude-ops delete`.
c) use `--no-clobber` https://github.com/odeke-em/drive#pushing.
*) Remotely, files are always trashed and not deleted immediately. You can use `drive untrash` or `drive trash` or `drive list --trashed` https://github.com/odeke-em/drive#trashing-and-untrashing.

Hope this helps.

**Comment by RickCogley** [comment]
hi @odeke-em, appreciate the answer! I'll work through that and see how it goes.

**Comment by RickCogley** [comment]
As an aside @odeke-em, I got it working well enough. This gist shows how: 

https://gist.github.com/RickCogley/bfdbe717753dd989a813

**Comment by RickCogley** [comment]
https://drive.google.com/open?id=0B3E_g6R5WF8Aa1ozSTdPTVZkM1k

**Comment by odeke-em** [comment]
Neat, good stuff, I think I might borrow your script :) Lots of times, I just wanna send screenshots to another device or back them up. If you were interested in that, and get bored, take a look at the `qr sharing` https://github.com/odeke-em/drive#qr-code-share

**Comment by RickCogley** [comment]
that might be useful, for sure. 

The one glitch I can see is, the ``https://drive.google.com/open?id=0B3E_g6R5WF8Aa1ozSTdPTVZkM1k`` path that I get back from the url verb is giving the "viewer" version of the link. This works to paste into many systems which understand it, such as HipChat or Flowdock. It does not work when pasted into Github issues, unfortunately.

**Comment by odeke-em** [comment]
Yeah that's a tricky one because in the past it used URLs prefixed by https://googledrive.com/host then fileId and that would work in some cases but only did so well for publicly shared files and didn't have a nice default opener, so I changed that up in https://github.com/odeke-em/drive/pull/355.

**Comment by RickCogley** [comment]
There was also ``https://docs.google.com/a/whatever/whatever`` :-)

**Comment by odeke-em** [comment]
Yeah but that only works for Google Docs + Sheets.

**Comment by RickCogley** [comment]
I don't understand it, but was testing an app called share bucket. It gives urls like: https://docs.google.com/a/esolia.co.jp/uc?id=0B3E_g6R5WF8AS3FmOUhhV0V2VFk

**Comment by RickCogley** [comment]
![](https://docs.google.com/a/esolia.co.jp/uc?id=0B3E_g6R5WF8AS3FmOUhhV0V2VFk)

**Comment by odeke-em** [comment]
Oh snap, is that from a custom app? I didn't know that, learnt something new today.

**Comment by RickCogley** [comment]
No, it's a little utility. It's pretty buggy, generally, so I wanted to figure out how to script it instead. https://fiplab.com/apps/sharebucket-for-mac

**Comment by odeke-em** [comment]
Btw if you don't mind, could you add your script to the wiki under a new heading called "Scripts" this way people can share, exchange and check out what others are doing.

**Comment by RickCogley** [comment]
Sure.

**Comment by odeke-em** [comment]
That's interesting. Once a friend of mine asked me to make him a script that would watch a directory or files and then on an action do something. I rigged something up here https://github.com/odeke-em/watnot/blob/master/watnot.go. Later on I had to write something for a project that would operate on modifications of inodes and it went pretty nicely, but unfortunately it is closed source + confidential, otherwise it could be an interesting alternative. If you are interested there are inotify modules that you could rig up and then make some hook up(drive can provide the uploading code without having to invoke a shell) for uploading to your public bucket. Actually some folks here might almost be on the same page https://github.com/odeke-em/drive/issues/446.

**Comment by RickCogley** [comment]
FYI, https://github.com/odeke-em/drive/wiki/%5BAutomation%5D-Scripts

**Comment by odeke-em** [comment]
Thank you thank you!

**Comment by RickCogley** [comment]
As I was looking I found another one that seems decent too: dropzone 3 (https://aptonic.com/). It's using a 3rd party script for Google Drive, which just does the upload and does not handle the getting of the url. Still, it's a neat app. 

Another one that I know works with Google Drive is Techsmith Snagit (https://www.techsmith.com/snagit.html). That is the most well developed I think, but, I hate the way their screenshots are bundled in a library which is hard to handle. The app itself does the trick and has good annotation, but, that weird library bundling drives me batty.

**Comment by RickCogley** [comment]
sure thing!

**Comment by RickCogley** [comment]
Ah, also, if I were using Windows I'd try this one: https://getsharex.com/

**Comment by RickCogley** [comment]
This format works in Github markdown: ``![](https://drive.google.com/uc?export=download&id=0B3E_g6R5WF8Aa1ozSTdPTVZkM1k)`` ... and if needed it would be possible to generate this URL in the shell script, because I can use ``drive`` to get the id.

**Comment by RickCogley** [comment]
I imagine these are fragile though; Google has a way of changing these things right under your nose.

**Comment by canpolat** [comment]
@RickCogley have you considered using a symbolic link instead of copying? That way, you don't have to delete the copied image or worry about deleting the images in Google Drive.

**Comment by RickCogley** [comment]
@canpolat that's what I've been mulling - how to get this working for real, in the best & most efficient way. 

Do you know, will ``drive`` operate on symlinks?

**Comment by canpolat** [comment]
`drive` successfully follows symbolic links. My whole workflow (in Linux) depends on that.

**Comment by RickCogley** [comment]
thanks @canpolat, I'll definitely keep that in mind.

**Comment by RickCogley** [comment]
@odeke-em @canpolat updated the script a little this AM. 

* Generified by putting variables instead of my stinkin' hard-coded paths.
* Changed the approach to use symlinks like @canpolat suggested (thanks!) 
* Added a popup to get a description and stick it in a variable for later use by ``drive``. This uses the mac-only ``osascript``, which lets you run applescript from the terminal. It just pops up a modal for you to type a description in, then uses that in a var to feed the file description to ``drive``. Better for later searching. 

https://gist.github.com/RickCogley/bfdbe717753dd989a813

**Comment by RickCogley** [comment]
As an aside, I'm monitoring my screenshots folder via Google's "Google Photos Uploader" as well. It is not a sync program, but just automatically uploads any photos it files in designated folders, to Google Photos. So I have my screenshots being uploaded to Drive, per this script here, and also to Google Photos in a different account. 

It would be nice if I could use the typed in description to write IPTC on the original file, if png's even allow that.

**Comment by canpolat** [comment]
@RickCogley, if you consider the question answered, could you please close the issue?

**Comment by RickCogley** [comment]
sure thing @canpolat
