### ISSUE TITLE
Unable to share a recently uploaded folder

### ISSUE THREAD

**Issue by elitecoder** [odeke-em/drive#570]
I can upload directories just fine, but cannot share them.

Neither using `--share` flag with `upload` verb, nor using `share` verb. Keep getting the following error -

`An error occurred: googleapi: Error 403: Insufficient permissions for this file, forbidden`

I am unsure what kind of permission issue this is, since from what I can see, drive has all the permissions over my Drive account.

**Comment by odeke-em** [comment]
Hello again @elitecoder.
So what version are you on?

**Comment by elitecoder** [comment]
Still v1.9.0. I would love to upgrade, but I am not sure where 
`go get -u github.com/odeke-em/drive/cmd/drive` is installing/building drive on my Mac OSX 10.11.

Any help would be much appreciated!

**Comment by odeke-em** [comment]
No worries, if your $GOPATH is properly setup it should be in $GOPATH/bin/
Feel free to add a wiki entry. So after the upgrade sharing will require you to enter atleast one email. If you want to make it publicly available then use publish. If it is an error of files not being writable or shareable because they are nested inside a directory you don't necessarily have writer access to, please see https://github.com/odeke-em/drive/issues/342.

**Comment by elitecoder** [comment]
You are super duper helpful! Since the arguments have completely changed, I'll try again and close the issue if everything works! Thanks again.

**Comment by odeke-em** [comment]
Am glad to be of helpful, and thanks for choosing drive. My apologies if I don't respond timely, I am currently very busy but in the next few months I'll hopefully get some free time.
