### ISSUE TITLE
Installing drive fails with errors

### ISSUE THREAD

**Issue by pafech** [odeke-em/drive#571]
SOLVED (was not odeke-em/drive related)

As Ubuntu 14.04 user I got this error:
```
$ go get -u github.com/odeke-em/drive/cmd/drive
# golang.org/x/sys/unix
src/golang.org/x/sys/unix/syscall_solaris.go:38: clen redeclared in this block
	previous declaration at src/golang.org/x/sys/unix/syscall_linux.go:784
src/golang.org/x/sys/unix/syscall_solaris.go:51: ParseDirent redeclared in this block
	previous declaration at src/golang.org/x/sys/unix/syscall_linux.go:797
src/golang.org/x/sys/unix/syscall_solaris.go:77: Pipe redeclared in this block
	previous declaration at src/golang.org/x/sys/unix/syscall_linux_amd64.go:108
src/golang.org/x/sys/unix/syscall_solaris.go:89: (*SockaddrInet4).sockaddr redeclared in this block
	previous declaration at src/golang.org/x/sys/unix/syscall_linux.go:291
src/golang.org/x/sys/unix/syscall_solaris.go:103: (*SockaddrInet6).sockaddr redeclared in this block
	previous declaration at src/golang.org/x/sys/unix/syscall_linux.go:305
src/golang.org/x/sys/unix/syscall_solaris.go:118: (*SockaddrUnix).sockaddr redeclared in this block
	previous declaration at src/golang.org/x/sys/unix/syscall_linux.go:320
src/golang.org/x/sys/unix/syscall_solaris.go:144: Getsockname redeclared in this block
	previous declaration at src/golang.org/x/sys/unix/syscall_linux.go:492
src/golang.org/x/sys/unix/syscall_solaris.go:153: ImplementsGetwd redeclared in this block
	previous declaration at src/golang.org/x/sys/unix/syscall_linux.go:164
src/golang.org/x/sys/unix/syscall_solaris.go:157: Getwd redeclared in this block
	previous declaration at src/golang.org/x/sys/unix/syscall_linux.go:168
src/golang.org/x/sys/unix/syscall_solaris.go:178: Getgroups redeclared in this block
	previous declaration at src/golang.org/x/sys/unix/syscall_linux.go:181
src/golang.org/x/sys/unix/syscall_solaris.go:178: too many errors
# google.golang.org/cloud/compute/metadata
src/google.golang.org/cloud/compute/metadata/metadata.go:55: unknown net.Dialer field 'KeepAlive' in struct literal
```

It turned out that
$ apt-get install golang
is still GO 1.2.

So I went ahead and followed
https://www.digitalocean.com/community/tutorials/how-to-install-go-1-5-3-on-ubuntu-14-04

all went well, but I still saw golang version -> 1.2.1
$ which go
revealed that I had the wrong binary pointed at:
/usr/bin/golang-go instead of /usr/local/go/bin/go
i.e. $GOROOT=/usr/local/go

Once I changed that, everything went smooth

**Comment by odeke-em** [comment]
As you mentioned, please use go > 1.2 and I'd recommend using go1.4.
I'll close this issue since you resolved it.

**Comment by nealmcb** [comment]
Is there some way, in the packaging of this code, to flag version errors earlier and just tell the user?

There are multiple issues here about this sort of compilation problem, and it is sad to see so many people who just expect this to run in a popular environment wasting their time just because they didn't notice the version issue. Or didn't have any idea how to install go. Or installed gccgo-go first on Ubuntu 14.04. I did all of those things, and am beginning to wonder if it is worth it to try yet again with a yet-more-customized installation.

Alternatively, it would help to at least warn people up-front in the README that there are many go implementations, and if they aren't familiar with go, they really need to be careful. E.g. they should not to assume they can just trust the advice they get when they run "go" and hear 

    The program 'go' is currently not installed. You can install it by typing:
    sudo apt-get install gccgo-go
