### ISSUE TITLE
false positive name clashes on pull

### ISSUE THREAD

**Issue by tachim** [odeke-em/drive#586]
Hi @odeke-em - first, thanks for maintaining this great package. I just tried it out and ran into a bug:

```
tachim@atlas-ws-2:/atlas/u/tachim/drive$ drive pull notes
Resolving...
These paths clash
X /notes/notes.otl 0BwIcfFfWC....
...

clashes detected. Use `ignore-name-clashes` to override this behavior or `fix-clashes` to try fixing this
```
There's nothing in the directory, though:
```
tachim@atlas-ws-2:/atlas/u/tachim/drive$ find .
.
./.gd
./.gd/credentials.json
./notes
tachim@atlas-ws-2:/atlas/u/tachim/drive$ 
```

Adding `-ignore-name-clashes` to the `drive pull` also has no effect. This is on commit `263f0d5b48f90c22f0c0bddaf61cc845ee007162` and Go 1.5.3.

**Comment by tachim** [comment]
Strangely, copying the same files into a folder called notes2 works!

**Comment by odeke-em** [comment]
Hello @tachim, thanks for the report and welcome to drive!

So the clashes that are reported come from the fact that Google Drive remotely allows many files to have the same name within the same directory, however your file system does not allow for this. This means that if you tried pulling 4 files all inside directory '/d1' and all sharing the name 't1', only one t1 will be pulled and this could lead to unexpected results because which t1 are you expecting?
There is an option that can help with fixing name clashes ie `--fix-clashes`, I'd recommend trying it out ;)

**Comment by tachim** [comment]
Hey @odeke-em - I'm confident that is not the issue because (i) all of the files in the directory had different names and (ii) copying all of the files to a folder called notes2 on another machine and then `drive pull`ing notes2 worked.

**Comment by odeke-em** [comment]
But now you realize that you are talking of `notes2` instead of `notes` as you had initially reported

### Before
<img width="684" alt="screen shot 2016-02-12 at 2 15 31 pm" src="https://cloud.githubusercontent.com/assets/4898263/13021983/23274614-d193-11e5-9e2b-eb97b6a2d74c.png">

### After
<img width="636" alt="screen shot 2016-02-12 at 2 18 12 pm" src="https://cloud.githubusercontent.com/assets/4898263/13022026/7ab68d90-d193-11e5-8a95-c543b0e67890.png">


Seems like you might have fixed the clashes by renaming to `notes2` from `notes` if drive gave you the prompt for that. You can always verify about the clashes you have by `drive stat` or `drive list` and as previously mentioned, clashes exist remotely on Google Drive and not on your file system.

**Comment by tachim** [comment]
Cool, turns out there was some sort of hidden item called notes that was conflicting with the folder. drive list helped. Thanks!
