### ISSUE TITLE
push keeps saying "no drive context found; run `drive init`"

### ISSUE THREAD

**Issue by RonJohn2** [odeke-em/drive#592]
(Freshly installed Go 1.6 and drive-google 0.3.4.)

There must  be something about the concept that I'm not understanding.

From $HOME, I ran this and pasted in the auth string

    $ drive-google init ~/gdrive
    Visit this URL to get an authorization code
    https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=BLAHBLAHBLAH
    Paste the authorization code: YADDAYADDAYADDA

    $ cd ~/gdrive
    $ mkdir hokum
    $ drive-google push hokum
    Resolving...
    + /hokum
    Addition count 1
    Proceed with the changes? [Y/n]:y

So far, so good.  Yet when I cd into ~/gdrive/hokum this happens:

    ron@haggis:~/gdrive/hokum$ drive-google push *
    Resolving...
     – 
    '/hokum/*' aka '/home/ron/gdrive/hokum/*' doesn't exist locally nor remotely

Yet directory hokum **does** exist under $HOME, under $HOME/gdrive and is visible in https://drive.google.com/drive/my-drive.  What am I doing wrong?

Thanks

**Comment by chevillet** [comment]
You should try ```drive-google push``` without the ```*```.

**Comment by RonJohn2** [comment]
Is the theory of operation that you must make directories under ~/gdrive that exactly match what's under $HOME, then cd into the ~/gdrive version of those subdirs to copy from the corresponding local dir into the remote dir?

**Comment by chevillet** [comment]
To be honest, I only use it the other way around, to download my Google Drive files to another machine (```pull```).
But, as soon as the init process is complete, you should be able to sync either the whole folder you just initialized **and its subfolders** (drive is recursive) or any of its subfolders:

- ```cd ~/gdrive && drive-google push``` to push all your local changes to Google from gdrive **and its subfolders**
- ```cd ~/gdrive && drive-google pull``` to update gdrive **and its subfolders** from Google
- ```cd ~/gdrive/hokum && drive-google push``` to push your local changes to Google from hokum **and its subfolders**
- ```cd ~/gdrive/hokum && drive-google pull``` to update hokum **and its subfolders** from Google

Hope this helps.

**Comment by odeke-em** [comment]
Hello @RonJohn2, thanks for reporting this and welcome to drive!

Thanks @chevillet for giving @RonJohn2 an answer.

`
Is the theory of operation that you must make directories under ~/gdrive that exactly match what's under $HOME, then cd into the ~/gdrive version of those subdirs to copy from the corresponding local dir into the remote dir?
`
No, it doesn't have to match anything under $HOME. In fact you can `drive init` anywhere on your filesystem that you have access to. I have multiple folders with different Google accounts on my machines. You can even drive init on /media/myUSB.

To debug this, please go into your gdrive and then list or stat for hokum
```shell
$ cd ~/gdrive
$ drive stat --depth -1 hokum
$ drive list --depth -1 hokum
```
If that reports that hokum is missing, please try to make sure you are using the one and same account otherwise ping this back.

**Comment by odeke-em** [comment]
Ping!

**Comment by RonJohn2** [comment]
I decided to stick with Dropbox.
