### ISSUE TITLE
error with installation

### ISSUE THREAD

**Issue by ManuCart** [odeke-em/drive#627]
Hi, I have this error when I try to update drive
````
go get -u github.com/odeke-em/drive/cmd/drive
# golang.org/x/net/context/ctxhttp
../.bin/go/src/golang.org/x/net/context/ctxhttp/ctxhttp.go:35: req.Cancel undefined (type *http.Request has no field or method Cancel)
````

**Comment by shaggytwodope** [comment]
Can you share the version of your go installation?

**Comment by ManuCart** [comment]
````
go version go1.3.3 linux/arm
````

**Comment by shaggytwodope** [comment]
I think this is related to changes in go and respective "libs". @odeke-em no doubt more informative then me. But without some code changes, `drive` might require a newer go version then 1.3 series.

Out of curiosity what os/distro are you trying to build on?

**Comment by ManuCart** [comment]
Ok thanks, it's a Raspian distrib for a Raspberry Pi.
I'm waiting...

**Comment by odeke-em** [comment]
Hello again @ManuCart thanks for reporting this. @shaggytwodope thanks for answering this.
Yes in deed, I think you need to have at least Go1.4 since request.Cancel was added in https://github.com/golang/go/commit/8b4278ffb75e79c277bfa90c5e473bfad9f7c1bd on 28th June 2015 but that was for Go1.5. Please try with Go1.4 for starters.

**Comment by ManuCart** [comment]
OK thanks it's working with 1.6.2

**Comment by ctro** [comment]
I ran into this same problem, the latest `go` fixes it for me too.
Maybe the README should be adjusted, it mentions go 1.3.x as a dependency. I was running 1.3 when the error above happened so I didn't think to update go.
