### ISSUE TITLE
Multiple accounts support (feature requests)

### ISSUE THREAD

**Issue by vzaliva** [odeke-em/drive#652]
I have several google accounts (university, work, personal) on each of them I am using google drive. It would be nice if 'drive' work similar to git. Each drive checked out to it's own folder with setting enclosed. The 'drive' command executed in such folder will use folder-specific settings.

**Comment by odeke-em** [comment]
Hello there @vzaliva, thank you for reporting this issue and welcome to drive.

drive from the very start has supported this. In fact I use drive for the same purposes with my different accounts ie UniversityX1, Personal X2, testingX1 and others. All you have to do is go into the root directory of what you account you want e.g
Say for example you wanted for the first time to initialize different accounts for `uni`, `work`, `personal` in your $HOME directory
```shell
$ mkdir ~/uni && cd ~/uni && drive init && cd $OLDPWD
$ mkdir ~/work && cd ~/work && drive init && cd $OLDPWD
$ mkdir ~/personal && cd ~/personal && drive init && cd $OLPWD
```
Every time that you go to `drive init` make sure to authorize the respective account
And now all you have to do is `cd ~/uni` or `cd ~/work` and you can use different account.s

This issue is a duplicate of https://github.com/odeke-em/drive/issues/362 which might contain a bit of more information or scripts.

**Comment by vzaliva** [comment]
Thank you for the explanation! It is important feature!
