### ISSUE TITLE
Push/Pull by file/folder id

### ISSUE THREAD

**Issue by AzureBlaze** [odeke-em/drive#667]
I think it would be a nice addition to download/upload with the file/folder id, it limits error for example with duplicate files/folders and it is shorter for very deep directories.

**Comment by odeke-em** [comment]
Hello there @AzureBlaze, thank you for the question and welcome to drive.

So this already exists for pull
```shell
$ drive pull --id 0fM9rt0Yc9RTPaDdsNzg1dXVjM0E 0fM9rt0Yc9RTPaTVGc1pzODN1NjQ 0fM9rt0Yc9RTPV1NaNFp5WlV3dlU
```
However this doesn't exist for push because with push you always have one unique resource with is the unique name of the file/directory on your file system.

Please see the README for more detailed examples.
