### ISSUE TITLE
Push or Pull always get file does not exist

### ISSUE THREAD

**Issue by staltux** [odeke-em/drive#679]
I follow the install structions but in the step

`drive pull`

it dont find the files

I am in ~/gdrive folder

pull and push files dont work

create new files with
`drive new file.txt`
create the file remote, but cannot download the file

obs: drive version: 0.3.7

**Comment by odeke-em** [comment]
Hello there @staltux, thank you for reporting the issue and welcome to drive.

Yap, this same issue was just reported in https://github.com/odeke-em/drive/issues/677 and has been fixed if you pull the latest source by `go get -v -u github.com/odeke-em/drive/drive-gen && drive-gen`.

**Comment by staltux** [comment]
Thank you, in the installation guide says that this command is to correct the different problem related to debug information in the binary file , just as I do not need debug information I skipped this step

this should be explicit more clearly in the README

**Comment by odeke-em** [comment]
Yes in deed, however the traditional way of installing in Go is just by `go get <package_main>` so `go get github.com/odeke-em/drive/cmd/drive`, however it is nice if a user could have their debug information baked in. When on a user reports an issue usually I'll do a one on one with them to discover where it occured, that's why I usually request using `drive-gen`. This is why I haven't emphasized its use in the README.

**Comment by staltux** [comment]
The problem is solved, I will close the inssue, thankyou for you support
