### ISSUE TITLE
quick pull

### ISSUE THREAD

**Issue by tgkprog** [odeke-em/drive#687]
like git has a -f which you can start git with. Go get some coffee and when you get back you know the operation is done! Can we have that with drive too? Now when I pull, first time am told, there are changes. So I : 
`drive pull --fix-clashes  MyPath `

Then it says "Clashes were fixed, please retry the operation"

Then it says do you want to really download (or something). Come on. Just one command :+1: 

`drive pull --fix-clashes --f --y  MyPath `

Or whatever you like, and do it all in one go! I want the remote on my local. I have taken care to back up, want you to over write or rename or anything, just do it please !

**Comment by odeke-em** [comment]
Hello there @tgkprog, thank you for creating this issue and welcome to drive!

So we do have an option to avoid the prompt. It is called `--no-prompt`
<img width="1280" alt="screen shot 2016-07-09 at 12 26 16 pm" src="https://cloud.githubusercontent.com/assets/4898263/16709814/60a824c0-45d0-11e6-965b-4012a35c20e2.png">

However given that lots of people have asked the same question expecting a `--yes` or `-y` option, we probably should make this an option e.g in this open issue https://github.com/odeke-em/drive/issues/637.

Since issue https://github.com/odeke-em/drive/issues/637 is still open, I'll close this one and we can move discussion there.

**Comment by tgkprog** [comment]
I suggest you add this to the home page help please (did not know you can do drive pull -h) thank you. works pretty well.
