### ISSUE TITLE
Ability to change chunksize

### ISSUE THREAD

**Issue by BrendenCA** [odeke-em/drive#706]
Hello @odeke-em 

I wanted to change the chunksize of the files being uploaded, so as to increase the upload speed.

I searched around in your code and couldn't find a way to manually change it

Can you help me?

**Comment by odeke-em** [comment]
Hello there @BrendenCA, thank you for the question and welcome to drive!

Hmm, so right now drive doesn't control any chunksizes. drive passes readers along to the Google API client after invoking the Media method of an upload request.

However, I can turn this into a feature request since the Google API client provides a function for chunkifying readers before Upload in a function called `PrepareUpload` https://github.com/google/google-api-go-client/blob/master/gensupport/media.go#L183
so we can detect if for example the chunksize is set then we can use that.

**Comment by odeke-em** [comment]
I forgot to tag and close this issue when I implemented that feature in https://github.com/odeke-em/drive/pull/840 in January 2017. Please get the latest by
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
```
and you'll be able to set it by
```shell
$ drive push --upload-chunk-size=16777216
```
which is what I use sometimes to upload in 16MB chunks.

Thank you for requesting for the feature and hope you enjoy drive. Cheers!
