### ISSUE TITLE
(documentation enhancement) Setting of GOROOT (OS X)

### ISSUE THREAD

**Issue by bjohas** [odeke-em/drive#727]
I would suggest that the installation documentation should say: 
"
If you have not used go before, create a project path for go (GOPATH) in your home directory, e.g. $HOME/go, and add this to your .bashrc/.profile etc:
export GOPATH=$HOME/go/
"

Also, following go instal from go set, I needed to manually set

export GOROOT=/usr/local/go/

Otherwise I got: "(import path does not begin with hostname)".

So perhaps this could be added to the instructions as well: 
"
Check that GOROOT is set in your .bashrc/.profile/etc, If it is not, then locate your go installation, typically /usr/local/go/ or ... or ... and add this to your .bashrc/.profile/etc, like this:
export GOROOT=/usr/local/go/
"

Thanks!

**Comment by odeke-em** [comment]
Hello there @bjohas.

Hmm, I prefer not to include $GOROOT in the README because a link to https://golang.org/doc/install is already included under section **Requirements**.
Under that guide, they go into detail on how to install Go on  different platforms. If you install Go correctly, drive's README in fact includes how to install your $GOPATH which is what we are more interested in.
<img width="1071" alt="screen shot 2016-09-10 at 2 49 41 pm" src="https://cloud.githubusercontent.com/assets/4898263/18413723/f2f07456-7765-11e6-9884-9c52d0a073fa.png">


Perhaps you could include this information in the wiki since it is for folks that might be stuck on bootstrapping go?
