### ISSUE TITLE
Error caused duplicate files

### ISSUE THREAD

**Issue by jimr6007** [odeke-em/drive#728]
I'm running via cron, every 15 min. Push and then the next pull. So two pushes and two pulls per hour.

looks like this:

15 * * * * cd /home/***/google-drive_*** && drive push -no-prompt
45 * * * * cd /home/***/google-drive_*** && drive pull -no-prompt

Occasionally a failure will happen resulting in various forms of corruption. 

For example:

Resolving...
googleapi: Error 500: Internal Error, internalError

This seemed to cause all files in one directory to be duplicated. Probably happened on the push.

I though about putting the comands in a wrapper script, test an ls first and if return code 0 go ahead with push but I'm not sure if that would have prevented this.

Any ideas?

Thanks !

**Comment by odeke-em** [comment]
Hello there @jimr6007, thank you for the issue and welcome to drive.

Ah this is unfortunate and is an artifact of back when drive was still premature.
I think we should make a 500 an error that doesn't relay back a "file not found" condition to prevent
duplicate files from getting created.

Let me investigate.

In regards to you wrapping drive in a script, the current behaviour hasn't changed, so I don' think this will alleviate the problem unfortunately.

**Comment by creighto** [comment]
Hey @odeke-em, first of all, thank you so much for maintaining this invaluable Linux client! It has been working great for me for a couple of days now.

But as of today, it seems to have stopped working entirely. I only keep getting the 500 error, e.g.

    > drive ls
    googleapi: Error 500: Internal Error, internalError

When trying to pull, it actually wants to erase my entire local folder… 💥 


Is there an option to make the output more verbose to debug the situation? -- Thanks.

**Comment by odeke-em** [comment]
Thanks for the report @creighto, my apologies for the erasive behavior. Yeah the remote file resolution could be fixed to ensure that we catch those pagination errors instead of just logging them. The source of the error is the use of awkward  functions during pagination that just return ```chan *File``` yet an error can occur during that file pagination.

I started on this, but I got to head to work in a few, so perhaps when I return home in about 9 hours or over the weekend.

For now you can disable deletions by `--exclude-ops delete` or `--no-clobber` during a push/pull.
Unfortunately there isn't a good debugging mode in drive, but I've gotten requests to improve it.

**Comment by odeke-em** [comment]
Hello there @jimr6007 and @creighto, thank y'all very much for the patience and for the bug reports.

I've fixed this behavior in https://github.com/odeke-em/drive/pull/741. Please get the latest from master!
