### ISSUE TITLE
unshare: No matches found

### ISSUE THREAD

**Issue by bjohas** [odeke-em/drive#747]
I'm getting the error "No matches found" when running:

drive unshare -emails somebody@gmail.com  -id some_id

I've tried adding "-role writer" (which doesn't really make sense, but just in case), but get the same result.

Does it mean that the ID is not found? or the email? I've double checked both.

**Comment by odeke-em** [comment]
Hello there @bjohas, thanks for filing the issue.

Great points that the error is confusing and doesn't make sense.

So the issue here is that the account type `--type` hasn't been specified. 
However, we should be providing a default account type, just like we do when one uses `drive share`.

Fixing this shortly!

**Comment by odeke-em** [comment]
@bjohas thank you for the patience and for reporting this issue.

Please get the latest from master!

**Comment by bjohas** [comment]
OK, great - thanks! Seems to work now!

While it worked, when I did
 drive unshare -emails xyz@gmail.com -id abc

I got this error:
 unshare err (document name with id abc): no matches found! 

Thanks!
