### ISSUE TITLE
StatusCode: 503

### ISSUE THREAD

**Issue by JonasXPX** [odeke-em/drive#752]
So, when I pull a file, I get this error, `pull: /WORKSPACE/Java-JSON/pom.xml err: download: failed for url "https://googledrive.com/host/0B6eAixP-e0ZZQmNlaDd1bUZFWm8". StatusCode: 503`
This has been repeated every day, and multiple accounts

**Comment by odeke-em** [comment]
Hello there @JonasXPX, thank you for reporting this issue and welcome to drive!

For starters, what version of drive are you using?
From the status code 503(service unavailable), I think you are running into  https://github.com/odeke-em/drive/issues/734#issuecomment-247090606.
If so, please get the latest code because Google shut down web hosting so that endpoint no longer exists.
If you might not know, you can get the latest by running
```shell
$ go get github.com/odeke-em/drive/drive-gen && drive-gen
```

Closing this issue, please reopen if it persists after getting the latests.

Thanks.
