### ISSUE TITLE
drive creates only 0 byte files

### ISSUE THREAD

**Issue by OliverHoffmann** [odeke-em/drive#764]
> drive -pull
pull: /Main.java err: download: failed for url "https://googledrive.com/host/0B45cEtTDvzfxcUNmMFZEMWhGVzA". StatusCode: 404
pull: /DiscCache.java err: download: failed for url "https://googledrive.com/host/0B45cEtTDvzfxTXVMamZhMGxzUWc". StatusCode: 404
....
Drive cannot pull any files, all my files are created locally but only 0 byte.
I do not have a proxy or anything like this, and direct access to Google Drive via Firefox works on the same computer.

**Comment by odeke-em** [comment]
Hello there @OliverHoffmann, thank you for reporting this and welcome to drive.

I do believe your drive is not up to date. Google Drive shut down /host/ID at the end of August 2016 starting I think in Europe. That was fixed in the last two releases with PR https://github.com/odeke-em/drive/pull/735.

Please get the latest by doing
```shell
$ go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by OliverHoffmann** [comment]
Thanks for the fast response, it seems the version in Gentoo is outdated then, the newest one here is 0.3.6 from May 2016. I will inform the maintainer of it.

**Comment by odeke-em** [comment]
Awesome, thank you!

**Comment by odeke-em** [comment]
And for those looking for answers, please see directly https://support.google.com/drive/answer/2881970?hl=en
