### ISSUE TITLE
[feature request] support rename

### ISSUE THREAD

**Issue by kcwu** [odeke-em/drive#85]

**Comment by odeke-em** [comment]
You read my mind, I was going to put up an issue for this in the morning.

**Comment by odeke-em** [comment]
@kcwu ping.

**Comment by odeke-em** [comment]
Can we then mark this as closed?

**Comment by kcwu** [comment]
My only remain concern is that `removeParent` before `insertParent` may cause file lost.

**Comment by odeke-em** [comment]
The only issue here is that if you insertParent before removeParent, there is a higher guarantee that the file will be parentless and declared garbage, even without a network loss if for example the oldParentId is equal to the newParentId, then the removeParent call at the end totally leaves it parentless. The fix for that will come with the "atomicity" that I explained in the comments. That is if for example during a network fail, try the operation again with an exponential backoff.

**Comment by kcwu** [comment]
Doesn't it help that compare oldParentId and newParentId before action?

**Comment by odeke-em** [comment]
I'll jump onto this in a day or two, homework dues calling. Unless you'd like to submit a patch :)

**Comment by odeke-em** [comment]
Btw this is applies to `move` not rename.

**Comment by kcwu** [comment]
fixed. thanks.

**Comment by odeke-em** [comment]
Thank you @kcwu, for the review and walk throughs!
