### ISSUE TITLE
help with Google Sheets exporting

### ISSUE THREAD

**Issue by dyburke** [odeke-em/drive#877]
Hi,

I really tried to scour the docs to figure this out, but I'm not sure if what I'm seeing is a bug.  When I pull a non-empty sheets file from drive, I get an empty file (0 bytes).  If I try to locally create a non-empty csv and push it, drive simply says everything is up-to-date and appears to do nothing; doesn't update the sheets mime type file and doesn't create a new (different mime type) file on drive.

I found the option to specify a mime type for a new file, but I don't see a way to force mime type of an existing file and forcefully update the file on drive.

Any help would be greatly appreciated; been working on this for 2 days... :(

**Comment by dyburke** [comment]
Also, by default, drive thinks everything is set to be ignored...  I created a .driveignore file and only put .gd in there, thinking that would cause it to ignore .gd and allow everything else, but that didn't work...

Some info on my setup:

go version go1.7.5 linux/arm

drive-google version
drive version: 0.3.9.1
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime:

**Comment by odeke-em** [comment]
Hello there @dyburke, thank you for the question and welcome to drive!

My apologies for the late reply.

So Google Sheets and Docs cannot be downloaded raw but rather exported, because they
are blobs that aren't directly exports by the Google Docs service. That file that you
see will always be empty on file before it is exported, so as to maintain consistency.
In order to export a file you'll need to pass in the output export types as comma separated
values, something like this:
```shell
drive pull -export odt,rtf,csv,tsv -explicitly-export <sheets_paths>
```

We talk about this in the README here:
* https://github.com/odeke-em/drive#exporting-docs under section Pulling
* https://github.com/odeke-em/drive#desktopentry under section DesktopEntry

**Comment by dyburke** [comment]
Sorry, I wasn't clear as to what my end goal was.  I would like to push a csv file, but push it in the sheets format so that other sheets can reference it. This is all I'm really attempting to accomplish; could you recommend a way to do that? -export doesn't appear to function with a push command.

**Comment by odeke-em** [comment]
Yeah, Google Docs and Sheets do not support reading or writing directly to those files.
Unfortuntely, no way around opening them to edit in the WebUI.

The other option you could do though is use the convert flag, but that barely works
```shell
$ drive push thisFile.csv -convert
```
and before we had a request for this issue from Google APIs but I think one of the PMs
closed it as non-actionable, I don't think there was anything they could do about it
The issue was https://github.com/odeke-em/drive/issues/232 and the Google APIs request was at https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=4198.

**Comment by dyburke** [comment]
Gah! This is such bad news. :(   Thank you for the help, @odeke-em ! Hopefully, they correctly implement the convert call since they never gave us a client at all... :/  I starred the issue and plan to share the tweet.  Thanks again!

**Comment by canpolat** [comment]
Hi @dyburke, I also had a similar setup where I needed to reference a CSV from another one. Since Google did not want to fix this issue, I went for a workaround.

1. Push the file without any conversions.
1. Open your Google Drive and get a shareable link for the file
1. Now, create a Google Sheet and (on cell A1 of the sheet) use the IMPORTDATA function to import data from your csv file into this spreadsheet. Typically the function call looks like this:

    =IMPORTDATA("https://drive.google.com/uc?export=download&id=YOUR-CSV-ID-GOES-HERE")

This will import all the data from CSV. Now, you can start working with this sheet. This is a feasible workaround in my case, but YMMV. Hope this helps.

__Caution:__ If you follow these instructions, the CSV file will have a public URL and if anyone gets hold of that URL they can access the contents. So, do not use this method if the contents of the file are important/critical/secret etc..

**Comment by dyburke** [comment]
@canpolat Thank you!!  I was poking around IMPORTDATA to work around this issue too, but I couldn't get my hands on the proper url to download the csv.

It is indeed a shame that I have to sacrifice security to make this work, but it's good enough for now.  Hopefully the drive team takes the feature req seriously and throws us a bone...
