### ISSUE TITLE
mistaking conflicts for clashes

### ISSUE THREAD

**Issue by Vagrantin** [odeke-em/drive#887]
First of all i want to thanks for this great tool which is very cool !
I'm trying to use the clashes command and -fix-clashes and I don't understand the behavior here:

```
$drive version
drive version: 0.3.9.1
Commit Hash: <CURRENT_COMMIT>
Go Version: <GO_VERSION>
OS: <OS_INFO>
BuildTime: 
```
I'm running the Debian packaged version of drive.
```
$cat /proc/version
Linux version 3.16.0-4-686-pae (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08)
```

So here is what i'm doing :

```
$drive clashes
no clashes exist!
```

```
$ drive pull mdu 
Resolving...
These 1 file(s) would be overwritten. Use -ignore-conflict to override this behaviour
X /mdu 0ByK8opLHf5ObeERCNWFaTeU0V0k
conflicts have prevented a pull operation 
```

```
$ drive pull -fix-clashes mdu
Resolving...
These 1 file(s) would be overwritten. Use -ignore-conflict to override this behaviour
X /mdu 0ByK8opLHf5ObeERCNWFaTeU0V0k
conflicts have prevented a pull operation 
```

Also tried this 

```
$drive clashes -fix-mode rename
no clashes exist! 
```

Finally, when run,

$drive -help 
There is nothing about clashes in documentation

but the command below is effectively working.

```
drive clashes -h
Usage of drive clashes:
  -depth int
    	maximum recursion depth (default -1)
  -fix
    	fix clashes by renaming or trashing all files
  -fix-mode string
    	set fix policy to rename or trash (default "rename")
  -hidden
    	allows operation on hidden paths (default true)
  -id
    	operate on clashes by id instead of by path
  -list
    	list clashes (default true)
  -no-prompt
    	shows no prompt before fixing clashes

```

So from here, either i don't understand at all how this is working or we may have a bug here?

Hope this is clear enough

Kindly

Matth

**Comment by odeke-em** [comment]
Hello there @Vagrantin, thank you for the question and welcome to drive! Also thank you for the kind words, I appreciate it.

So conflicts are NOT clashes(name clashes).

## Conflicts
When both sides modify a file and we don't know which file overwrites the other, in this case the user will have to take over manual mode and go pull that file themselves. We capture such information in the .gd/drivedb database records modification times and sizes plus other necessary information, and then compare if the modTimes and checksum are different.

## Clashes
These occur when more than one file/folder has the same name in the same parent folder. This
is because Google Drive permits you to have duplicated file names but your file system cannot handle. Clashes are handled as you had tried with the command `clash` and with `pull -ignore-clash`.

## Fixing your problem:
The README talks about how to deal with conflicts and how to ignore them so clobber the data if the user doesn't care as shown here https://drive.google.com/open?id=0By5qQkvRAeV2QWdKY1RNbTBpVEU


it can be done by using flag `-ignore-conflict` in a push or pull e.g
```shell
$ drive pull -ignore-conflict
```
Also the failing command mentions that you should use `-ignore-conflict` as shown https://drive.google.com/open?id=0By5qQkvRAeV2ZEdONi10SW16dHc

Hope this helps.

**Comment by Vagrantin** [comment]
Ok thanks now I get it ! Thanks for the clarification.

PS: Still on my release (0.3.9.1), there is nothing about clashes in drive -h.

Thanks a lot !

Matth
