### ISSUE TITLE
Receiving "syntax error: unexpected string literal, expecting comma or )" With Both Go 1.7 and 1.8

### ISSUE THREAD

**Issue by jjyu98** [odeke-em/drive#889]
Hello,

I'm receiving this error, like previous issues, but with go version 1.7.4, 1.7.5, and 1.8 (amd64):

go get -u github.com/odeke-em/drive/cmd/drive
\# github.com/odeke-em/drive/cmd/drive
go/src/github.com/odeke-em/drive/cmd/drive/main.go:33: syntax error: unexpected string literal, expecting comma or )

Ubuntu 16.10 yakkety, x86_64

**Comment by varunkamath** [comment]
I am having this issue as well on Ubuntu 16.04.

https://hastebin.com/yoliligano.vbs

**Comment by odeke-em** [comment]
Hello there @jjyu98 and @varunkamath, thanks for the question and welcome to drive.
Are y'all sure you aren't running on less than Go1.7?

This package has been used on every Go version since Go1.4 with no problems, in fact I've just compiled it right now with the latest Go which is right after Go1.8. And that line doesn't make sense because that's an import line

<img width="722" alt="screen shot 2017-03-04 at 9 53 06 pm" src="https://cloud.githubusercontent.com/assets/4898263/23584667/fab5f55a-0124-11e7-9b52-e8ee9ab06f20.png">

If compiling is causing a bit of trouble, there are PPAs for different distros https://github.com/odeke-em/drive/blob/master/platform_packages.md by various contributors and also in the releases I usually compile binaries for them https://github.com/odeke-em/drive/releases/tag/v0.3.9.

**Comment by jjyu98** [comment]
Thanks for the prompt response.

Yes I checked the Go version in /usr/local/VERSION and saw that it was 1.8 (and 1.7.X for the other versions I tried). I'm not really sure what's causing the error.

But I added the twodopeshaggy repo for Ubuntu from the platform packages link you provided, and it seems to be working great. I look forward to using drive. I appreciate your work!

**Comment by shaggytwodope** [comment]
@jjyu98 ANY problems contact me asap and I'd be happy to fix the ppa right away.

**Comment by jjyu98** [comment]
@shaggytwodope Sounds good. Thanks so much.

**Comment by odeke-em** [comment]
@jjyu98 glad to know that @shaggytwodope's PPA resolved it.
Not all heroes wear capes, thank you @shaggytwodope for the good work and for offering to help out!
