### ISSUE TITLE
PPA Failed to fetch. Hash Sum Mismatch.

### ISSUE THREAD

**Issue by telemarker7** [odeke-em/drive#897]
Hi,

I'm running Ubuntu 16.04. When I run ```sudo apt-get upgrade``` I get the error
```bash
Get:1 http://shaggytwodope.github.io/repo ./ aptdaemon-data 1.1.1+bzr982-0ubuntu16 [161 kB]
Err:1 http://shaggytwodope.github.io/repo ./ aptdaemon-data 1.1.1+bzr982-0ubuntu16
  Hash Sum mismatch
Fetched 131 B in 0s (1,247 B/s)       
E: Failed to fetch http://shaggytwodope.github.io/repo/./all/aptdaemon-data_1.1.1+bzr982-0ubuntu16_all.deb Hash Sum mismatch
```
I've removed and re added the PPA and the key.

How do I resolve this error since it prevents any other updates?

**Comment by shaggytwodope** [comment]
This is not a ppa, and not even ment for ubuntu. This package is also not even related to drive. Any reason why you may have installed it?

That aside, check out [this](http://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error) webpage.  The instructions for ubuntu can be found [here](https://github.com/odeke-em/drive/blob/master/platform_packages.md#ubuntu-or-ubuntu-based-distros). If you find any confusion in the steps given please share so that it may be improved and clear up any misunderstanding.

**Comment by telemarker7** [comment]
Ahh, wrong distro. I knew it was a stupid mistake which was staring me in the face.

**Comment by shaggytwodope** [comment]
@telemarker7 no such thing, in fact you did what many don't... ask for help. Today you learned something, and feel free to ask for help again. Close the issue if it is indeed solved for you.

**Comment by telemarker7** [comment]
Thanks
