### ISSUE TITLE
open: .driverc parsing is missing

### ISSUE THREAD

**Issue by fabianbl** [odeke-em/drive#902]
My `~/.driverc` looks like this:

```bash
[pull]
desktop-links=false

[open]
file-browser=false
```

However, these arguments are ignored when running `drive pull` or `drive open` (Desktop links are still created and file browser is opened).

Did I miss something there? Other arguments like `export=pdf` seem to work fine, so the `~/.driverc` file is not completely ignored.

**Comment by odeke-em** [comment]
Hello there @fabianbl, thank you for the bug report and welcome to drive.

I think this is a case of avoid the "zero value" since by default each boolean value is false, so the logic in the way we are processing .driverc entries is skewed for zero values leaving them as if they were unset. Let me examine this case and fix it. Good catch, thank you.

**Comment by odeke-em** [comment]
Found the problem, .driverc wasn't implemented for the open command. Each command has to have that implementation individually. Fix coming up in a second.

**Comment by odeke-em** [comment]
Thank you very much for the bug report @fabianbl, I've fixed the bug with PR https://github.com/odeke-em/drive/pull/906.

Please get the latest drive by
```shell
$ go get -u github.com/odeke-em/drive/drive-gen && drive-gen
```

and it should be fixed!

**Comment by fabianbl** [comment]
Thank you a lot for the quick fix @odeke-em!
