### ISSUE TITLE
Pull deletes files that don't exist locally?

### ISSUE THREAD

**Issue by haydenm315** [odeke-em/drive#905]
"The pull command downloads data that does not exist locally but does remotely on Google drive, and may delete local data that is not present on Google Drive. Run it without any arguments to pull all of the files from the current path:"

Why delete local files that don't exist remotely?  I think this may have just happened to me, and now I'm out of an important file.

**Comment by canpolat** [comment]
As you have quoted, this behavior is well documented. drive is a synchronization program, and by default it synchronizes the non-existant (deleted) files as well as the others. You are asking "why?" Well, because the designers of the program decided that way.

I think this issue can be closed.

**Comment by odeke-em** [comment]
Hello there @haydenm315, thank you for the question and welcome to drive!

Yeah, that's the only we can sync files in order to match the contents/structure on both sides.

There are two safe options to prevent deletions:
a) --exclude-ops=delete
```shell
$ drive pull --exclude-ops=delete
```
which will prevent delete operations from occurring

b) --no-clobber
```shell
$ drive pull --no-clobber
```
which will prevent any data overwrites so no modifications nor deletions, just additions.
Whichever option you choose might impact you in that you'll always have modifications going on everytime you pull or push, but that's left to your discretion.

Thank you @canpolat for helping to answer the question!
