### ISSUE TITLE
Question: Push only

### ISSUE THREAD

**Issue by mikecarr** [odeke-em/drive#924]
Is it possible to only push ? I am pushing from multiple clients, if one client does not have the same files as the other it removes them from drive.

**Comment by odeke-em** [comment]
Hello @mikecarr, thank you for the question and welcome to drive!
 
Yes, it is possible to push only, with options:
1) Use `--no-clobber`:
Using this flag with a push means that only add, don't modify nor delete nor touch e.g
```shell
$ drive push --no-clobber content 2014/Reports
```
2) Use `--exclude-ops`:
Using this option requires you to ultimately describe which CRUD operations you'd like to exclude e.g
* Create
* Read
* Update
* Delete
To avoid any deletions and updates
```shell
$ drive push --exclude-ops update,delete .
```

I'd recommend option 1) since it is simpler to type out and doesn't require much context.

Please let me know if you have any other questions, and I'll close the issue, feel free to reopen if anything is unclear. Thank you!
