### ISSUE TITLE
[feature request] Options for diff

### ISSUE THREAD

**Issue by ikwyl6** [odeke-em/drive#93]
`drive diff -files [-depth $N] $DIR` - Show only diff on files

`drive diff -dirs [-depth $N] $DIR` - Show only diff on 1st level parent directories

`drive diff -remote [-depth $N] $DIR` - Show only "only on remote" files/dirs

`drive diff -local [-depth $N] $DIR` - Show only "only on local" files/dirs

`drive diff -short [-dirs | -files | -remote | -local] [-depth $N] $DIR` - Show short version of diff information

`drive diff -long [-dirs | -files | -remote | -local] [-depth $N] $DIR` - Verbose info on diff

**Comment by odeke-em** [comment]
Nice, I like this, seem like neat specs.

**Comment by ikwyl6** [comment]
Any chance of getting this implemented?

**Comment by odeke-em** [comment]
Hello @ikwyl6 thanks for the reminder. I've been mainly fixing bugs and working on show stoppers/critical features. However, soon this will will be added ;)

**Comment by ikwyl6** [comment]
ping!

**Comment by odeke-em** [comment]
pong.

**Comment by odeke-em** [comment]
Not yet worked on this :(

**Comment by odeke-em** [comment]
Hello @ikwyl6 during a study break, I got time and looked at this request. I've implemented the `--depth` depth traversal diffing, that's a great suggestion as it will be carried over later on push and pull. You can see the progress at this PR https://github.com/odeke-em/drive/pull/411

However, I've found a couple of things that didn't quite make sense
1)
```shell
$ drive diff -files [-depth $N] $DIR - Show only diff on files
```
"--files" doesn't make the cut since diffing happens only on files implicitly, the warning for diffing on directories would just be masked by that option, also introducing complexity in the search for items.

2)
```shell
$ drive diff -remote [-depth $N] $DIR - Show only "only on remote" files/dirs
```
This option doesn't make the cut because diffing is meant to find files that are not present both locally and remotely.

3)
```shell
$ drive diff -local [-depth $N] $DIR - Show only "only on local" files/dirs
```
Clause 2)'s reasoning applies here

4)
```shell
$ drive diff -short [-dirs | -files | -remote | -local] [-depth $N] $DIR - Show short version of diff information

$ drive diff -long [-dirs | -files | -remote | -local] [-depth $N] $DIR - Verbose info on diff
```

**Comment by odeke-em** [comment]
Please get the latest from master, you should now be able to diff until a depth.
Thanks for the patience :)
