### ISSUE TITLE
push does not upload new versions after first version

### ISSUE THREAD

**Issue by andmatand** [odeke-em/drive#940]
Okay there's this weird thing that has happened to me twice now (version 0.3.9.1 on macOS Sierra)

1. Create a file locally
2. Push it
3. Make edits to the file
4. Push it again
5. Repeat 3 - 4 multiple times
6. Go to another computer (Linux) and pull

Expected: the file I pull is the most recent version
Actual: the file I pull is the first version I pushed from the other computer

I look in drive.google.com at the file, right click and go to "Manage Versions" and it says there is only one "version" even though I pushed multiple successive versions (and the pushes purported to be successful)

I've tried `push --force` and that doesn't seem to make a difference...

The other weird thing is that in drive.google.com it lists the file's modification time as the time of the last push, yet when I look in "Manage Versions" there is only the one (first) version and its time is the time of the first push.

The only thing I can do is manually upload a new version via the web UI.

I've been using this amazing program for 2+ years and this just started happening recently, around the time that I noticed Google added that "Manage versions" feature, so maybe it is related to API changes or something.

This is obviously a serious issue because it could result in lost work totally transparently. Let me know if there's anything more info I can provide.

**Comment by odeke-em** [comment]
Hello there @andmatand, thanks for reporting this and welcome to drive!

So would you mind giving an actual sample of a file and how to make those edits?

If the file size remains the same, by default we won't push it unless you use
`--ignore-checksum=false` as per https://github.com/odeke-em/drive#verifying-checksums which is the common case for most users. In the past drive was sensitive enough and would push up any file change but this was found to unnecessarily consume CPU and bandwidth verifying checksums everytime so we only perform checksum if that flag is set. It is a tradeoff that we found necessary since folks complained about speed.

From the symptoms it seems like the filesize remained the same and any edits just caused modTime changes(modTime can be changed without uploading or downloading any content).

**Comment by andmatand** [comment]
Ah! You are exactly right. I am changing the file contents without changing the size. (This is a common workflow for editing tracker music in PICO-8 files where the data allocated to the music is a fixed size) That explains it!

Okay so then the UI seems pretty darn misleading in this case, because it shows all the same progress bar and everything as if it is uploading the file contents...is that not what it was doing? I would expect that it would instead say something like "filesize hasn't changed...updating timestamp". So I think there's room for improvement there.

Also it seems to me that "force" should have done the job here. The documentation says it "forces a push even if no changes present" and that does not seem to be what it did in this case. I think the `--ignore-checksum=false` behavior should be added to the behavior of `--force`. I told it to push one specific file, with the `--force` flag...in most CLI syntax you literally cannot get any more explicit than that lol. So I did not imagine there could be another flag that would be more _forceful_ :)

**Comment by markbirbeck** [comment]
might be an idea to close this issue if the answer is satisfactory. when flicking through the issue list it gives the impression that there is a serious problem!

**Comment by andmatand** [comment]
Yeah, good idea. I'll make a different issue for the UI issue(s).
