### ISSUE TITLE
Time to push to destination increases with directory size

### ISSUE THREAD

**Issue by andrewrapp** [odeke-em/drive#947]
I'm pushing images to a destination and I noticed the drive-push process time is increasing as the destination directory grows. Essentially I just want to push whatever is in the local folder (not mounted or sync'd with gdrive) and delete from it after the push completes, as a constant time operation ex:

drive push -ignore-checksum -ignore-conflict -no-clobber -no-prompt -ignore-name-clashes -verbose -destination raspi ~/sync && rm ~/sync/*

Now there are about a 1000 files in the "raspi" gdrive folder and it takes about 3 minutes to push. Initially it took just seconds. Is there anyway to speed this up or do I need to be creating new directories periodically to avoid this situation?

**Comment by odeke-em** [comment]
@andrewrapp thank you for the issue and welcome to drive! My apologies for the late reply, I've been swamped with work.

So unfortunately each file has to be operated on individual, there isn't a bulk upload nor is there a diff-patch mechanism as Google Drive doesn't support one. We support uploading in parallel those but the bottleneck here would be the uplink speed and bandwidth.

It seems that your concern is that as the number of files in a directory, so does the push time, right? I don't yet see a way around this as we push files in parallel, irrespective of directory. By https://github.com/odeke-em/drive/wiki#env-variables or you can take advantage of already open connections and instead increase the chunk size per file uploaded e.g instead of the default of 8MB chunk size, to set it to 16MB
```shell
$ drive push --upload-chunk-size 16777216
```

I hope this helps, but otherwise unfortunately I don't think I am of much help here.

**Comment by andrewrapp** [comment]
Hi @odeke-em, I ended up using the google drive api. For what I needed it was quite simple to implement and it seems to have constant time performance w.r.t folder size

**Comment by odeke-em** [comment]
Nice, good to know you were able to solve the issue :) Thanks for checking out drive. One day hopefully we'll be able to solve it here on drive.
