### ISSUE TITLE
Any expected issues by shut down of Google Drive app on PC?

### ISSUE THREAD

**Issue by ApolloCrw** [odeke-em/drive#948]
Hello

Actually I think I know the answer, but just to be sure and also to answer this for another people. So question is:

Following [this post](https://gsuiteupdates.googleblog.com/2017/09/drive-file-stream-from-google.html) Google Drive app on PC/Mac will be shut down on March 12th, 2018. Will this affect by any way this project, like is the api of google drive changed, or they just shutting down app and that's all?

thanks

**Comment by millenc** [comment]
Any more info on this? @ApolloCrw have you been able to find out if this application will keep working?

**Comment by odeke-em** [comment]
Hello there @ApolloCrw and @millenc, thank you for the question and welcome to drive! My biggest apologies for the late reply, I've been swamped with a bunch of work.

So that post talks only about the old Google Drive client, which is unrelated to drive. The only thing that I would be concerned about is if Google announced that they would deprecating the `drive/v2`  API, which they haven't announced. However, we should move to the `drive/v3` as I've seen requests for things like `Team Drives` etc.
Also this FAQ from Google talks about downloading the latest Google Drive UI/Desktop client https://support.google.com/a/answer/2490101.

**Comment by odeke-em** [comment]
Hello there @ApolloCrw and @millenc, thank you for the question and welcome to drive! My biggest apologies for the late reply, I've been swamped with a bunch of work.

So that post talks only about the old Google Drive client, which is unrelated to drive. The only thing that I would be concerned about is if Google announced that they would deprecating the `drive/v2`  API, which they haven't announced. However, we should move to the `drive/v3` as I've seen requests for things like `Team Drives` etc.
Also this FAQ from Google talks about downloading the latest Google Drive UI/Desktop client https://support.google.com/a/answer/2490101.

Therefore, I am not worried about drive not functioning as Google hasn't made any indication of shutting the `drive/v2` and `drive/v3` APIs
