### ISSUE TITLE
Drive creates clashes pushing directories

### ISSUE THREAD

**Issue by tigerjack** [odeke-em/drive#951]
Suppose the following offline structure
```
Test
└── a
    └── b
        └── c
            ├── tmp.1YZgcY
            ├── tmp.9Pyx3i
            ├── tmp.ERLIlA
            ├── tmp.Hz2b4U
            ├── tmp.JpOqrW
            ├── tmp.MV2TkJ
            ├── tmp.pELizH
            ├── tmp.UGortb
            ├── tmp.vECS2r
            └── tmp.xJTmBd
```
None of this files or directories is available online.
When I try to push the whole `Test` directory `drive` will always generate directories with the same name in one of the layers of the hierarchy. Also, the push will complete without warnings or errors, but at a following pull/push it will warn you of detected clashes.  

I think that the problem is due to the concurrent execution of multiple threads. If each one of the files will execute on a different thread, each one will try to create the directory structure, resulting in multiple directories with the same name created online. 

To avoid the problem, I'm using a simple workaround with a bash for loop: `for i in {1..15}; do drive push -depth=$i /my/dir; done`. Of course you can replace 15 to whatever maximum depth you want.
The problem with this approach is that it's time-expensive; also, because I don't remember at all my online/offline directory structure and because the push will not give any warning, I often simply run a `drive push` without even thinking it will be a problem.

Maybe, to avoid the problem, a solution could be to simply recreate the directory structure in just one thread, and only later try to push the various files. However, I have no clue about go and its concurrency mechanism, so maybe this is just not feasible. In this case, there is a way to fix the number of concurrent threads?

**Comment by NesbiDevelopment** [comment]
Hello tigerjack, does this specific hypothetical offline structure cause the duplicate folders every time?

Because I experience similar issues, but only with very specific character set contained in the directory, that is to be pushed.
Your example does not result in duplicate folders when I was testing it.

But every push with a directory that contains a special character in uppercase (e.g. ÄÖÜÆẞ) will cause duplicated folders for me. (And therefore cause name clashes)

Example 'Ä'
![a](https://user-images.githubusercontent.com/23743591/33851497-70f4403a-deb7-11e7-8b5a-89afff43811b.png)
This will result in duplicate folders every time (tested with ÄÖÜẞÆ, at the beginning, middle and and of folder names)

Google drive online:
![a](https://user-images.githubusercontent.com/23743591/33852212-effa0336-deb9-11e7-8e2e-5012fdb2b7aa.png)

Lower case special characters seem not to be affected:
![a](https://user-images.githubusercontent.com/23743591/33851482-6d689934-deb7-11e7-8921-67ee75c476e1.png)

Tested on Solus (drive from repository) and an the bash-emulator "Termux" on Android (from source). 
Each with the newest version (0.3.9.1). 
I only did experience this issue since about 2 months ago, but I did have many directories with uppercase Ü since I began using drive (the word "Übungen"->"exercises" is quite useful in university as a german ;) )

After a few test, I'd say that drive currently can't find/match folders/directories with a uppercase special character.
This can also result in "Everything is up-to-date" or the request to "Delete everything".
![invisible](https://user-images.githubusercontent.com/23743591/33852588-68b4ca3a-debb-11e7-8186-c5a0e566b38a.png)

I hope this helps to narrow down the error. 
I'm currently to occupied to look into the go lang and the drive code myself ;)

A current workaround that helped me is exchanging every uppercase special character with a different character.

**Comment by tigerjack** [comment]
@NesbiDevelopment IIRC, at the time of this post I precisely run the same example of the post and the same behavior appeared. So, I think that your problem is more general and related to the encoding of characters.

**Comment by davidhcefx** [comment]
Hi everyone,
I wrote a workaround script according to @tigerjack 's observation.
Please feel free to use and modify it!

	#! /bin/bash
	# This script works as the original "drive push [options][target]",
	#   but would avoid the bug of creating multiple clashing directories (Bug #951)
	# Written by davidhcefx, 7,Feb,2018

	getMaxDepth(){
		L=0
		R=20
		# Set Right bound
		res=`find $target -mindepth $R`
		while [ "$res" != "" ]; do
			R=$((R+5))
			res=`find $target -mindepth $R`
		done
		# Binary search
		while (( L+1 < R )); do
			M=$(((L+R)/2))
			res=`find $target -mindepth $M`
			if [ "$res" != "" ]; then
				L=$M
			else
				R=$M
			fi
		done
		echo $((R+1))  # note that drive's depth = find's depth+1
	}

	target=`pwd`
	if [ $# != 0 ]; then
		for i in "$@"; do :; done
		if [ -f "$i" ] || [ -d "$i" ]; then
			target=$target/$i
		fi
	fi
	maxdepth=$(getMaxDepth)
	i=1
	while [ $i != $maxdepth ]; do
		drive push -no-prompt -depth $i $@
		i=$((i+1))
	done

**Comment by davidhcefx** [comment]
asfdfdf

**Comment by odeke-em** [comment]
Hello there @tigerjack thank you for reporting this issue and in addition welcome to you, @NesbiDevelopment and @davidhcefx all to drive!

My apologies for the late reply, I've been heavily swamped with work. Yeah we've experienced this problem before but I thought we no longer had it.

In the future, it might be useful to report your drive version by `drive version`, because many reports come through with versions of drive for which patches were already made. Perhaps for starters let's begin by you @tigerjack providing your `drive version`.

>Maybe, to avoid the problem, a solution could be to simply recreate the directory structure in just one thread, and only later try to push the various files. However, I have no clue about go and its concurrency mechanism, so maybe this is just not feasible. In this case, there is a way to fix the number of concurrent threads?

This is a great idea and one that we already have though
https://github.com/odeke-em/drive/blob/a6b4c6a5125c77fed710e4270cd0d21b460753f1/src/push.go#L470-L552

**Comment by tigerjack** [comment]
Hei @odeke-em, here it is
    drive version: 0.3.9.1

I think it's the most recent one, but I may be wrong.

**Comment by odeke-em** [comment]
In deed, you are on the latest, thanks for the confirmation @tigerjack! 

Giving it a second look, I perhaps see a bug creeping in at 
https://github.com/odeke-em/drive/blob/a6b4c6a5125c77fed710e4270cd0d21b460753f1/src/push.go#L506-L515
we could replace all the mkdirAllMu.Lock() and mkdirAllMu.Unlock() invocations with a single
```go
mkdirAllMu.Lock()
defer mkdirAllMu.Unlock()
```

**Comment by davidhcefx** [comment]
Mine also 0.3.9.1
That looks like solving the problem, but I'm not familiar with golang so I can't guarantee that

**Comment by pirates712** [comment]
@odeke-em, I tried replacing all the mkdirAllMu.Lock() and mkdirAllMu.Unlock() invocations with a single
`mkdirAllMu.Lock()
defer mkdirAllMu.Unlock()`

but I think the problem is the mkdirAllMu mutex is non-recursive, so you have to release it before recursively calling g.remoteMkdirAll(). If you don't, the program deadlocks.

I was able to work around the issue by changing the line
`results := semalim.Run(jobsChan, uint64(n))`
to
`results := semalim.Run(jobsChan, uint64(1))`
which seems to make it single threaded.

**Comment by PandyTheBroh** [comment]
Hi @odeke-em and @pirates712 .

In my work we use intensely the drive cli and I have been suffering this issue in the last weeks strongly. 

I have tried to develop a custom version to resolve it using your last messages, but my knowledge of Golang are scarce. 

Could you create a testing/fix/something branch with this temporal solution to test it?

**Comment by odeke-em** [comment]
Hello there everyone! My apologies for the lack of activity, I have been very busy with lots of work and projects. However, today I got sometime and fixed this issue by making only one goroutine exclusively invoke remoteMkdirAll. Please get the latest from master and thank you all very much for the patience and for using drive over all these years!
