### ISSUE TITLE
[NOT A BUG] Question about possible issues with dual booting

### ISSUE THREAD

**Issue by manugutito** [odeke-em/drive#956]
Hey there,

I have a dual booting machine (gentoo+win10) and I was wondering if there are any known issues that can be caused by having drive and the official Windows client work on the same folder (I don't want to have two local copies). Aside of course of filenames that are illegal for Windows.

Thanks!

**Comment by odeke-em** [comment]
Hello there @manugutito, thank you for the question and welcome to drive! My apologies for the late reply, I've been swamped.

So drive only needs to use the .gd directory to store credentials so as long as the Windows client doesn't muck with that directory there shouldn't be a problem. Of course if the Windows client adds its own configuration files that make drive to need a push or pull, it'll report changes.

The issue though that I can see is that the Windows client might upload your .gd directory to Google Drive and if someone else has access to this directory, they can steal your credentials, so please be cautious about that.

Otherwise, I'll close this issue. Please feel free to reach out or reopen this one in case of any more questions. Thank you!
