### ISSUE TITLE
disable pulling of empty .desktop files for Google Docs and Google Sheets

### ISSUE THREAD

**Issue by yuri0r** [odeke-em/drive#958]
so i installed from master today using go get -u and made the drive init and tried to pull my entire gdrive which worked flawlesly but i noticed that every gdocs .desktop file comes with an empty file with the same name (but without fileneding)
i am curious if this is by design and if so how i can disable that? 
running lubuntu 16.04

**Comment by odeke-em** [comment]
Hello there @yuri0r, thank you for the question and welcome to drive. My apologies for the late reply, I've been swamped.

We already have this feature that can be disable with `-desktop-links=false` and it is documented in the README at https://github.com/odeke-em/drive/blob/0b501d3138b75d59aafa5157c76c2aa164aa2e11/README.md#desktop-files
```shell
$ drive pull --desktop-links=false mydocs
```

And yes it is by design so that you can click on those files and directly open up the files in the Google Drive Web UI.

Thanks again, please feel free to reopen if the mentioned remedy doesn't work.

**Comment by felipegallego** [comment]
hello @odeke-em I have one question:
Why when pulling a google doc, it creates two files? One is useful, the *.desktop you can click on it to open in the brower. But what about the second empty file? Can drive be configure so that, when pulling a google doc, it ONLY creates a *.desktop file but NOT an empty file? Thank you in advance.
