### ISSUE TITLE
Enhacement Request : Check the File before downloading from remote

### ISSUE THREAD

**Issue by TheNetworker** [odeke-em/drive#969]
Dears,

Do we have a way to not download/pull the entire Google Drive from Internet if I have a recent and latest copy in my HDD? For example user will copy the content of HDD to the Linux machine and inform the `drive` to work on them directly without downloading again from Internet (basically to save bandwidth and time)
We can depend on md5sum and execute `drive diff` before push/pull operation

**Comment by odeke-em** [comment]
Hello @TheNetworker, thank you for the question and welcome to drive.

We already have this in and this is the way that drive has operated from the beginning, checksum differences prompt pulls/pushes otherwise noop. I suspect you figured out that out and hence closed this issue. 

Please feel free to check around and hope you enjoy using drive!

**Comment by TheNetworker** [comment]
Hello @odeke-em 
Thank you for clarification, Yes at the beginning I thought it would download the whole drive from the internet (cause it took some time to finish `Resolving`)
Thank you for this great tool.
