### ISSUE TITLE
how do I compile Drive On Windows Using Go

### ISSUE THREAD

**Issue by nassausky** [odeke-em/drive#974]
I found instructions on this site how to get use go to download Drive from the repository and install the package.  How might I do this manually in Windows?

I tried the following:
    go install
    go build
but not sure which directory to run it from or if I have to add any parameters to the commandline and if I have to configure anything ahead of time.

**Comment by odeke-em** [comment]
Hello again @nassausky, thank you for the question.

So if you've installed Go properly, all you have to do is run this single command documented in the README https://github.com/odeke-em/drive#from-sources that is
```shell
go get -u -v github.com/odeke-em/drive/cmd/drive
```
or with more diagnostic information
```shell
go get -u -v github.com/odeke-em/drive/drive-gen && drive-gen
```

**Comment by nassausky** [comment]
Yep that did work and it hid the installation binary file in a path I wasn't expecting. Thanks I was just curious if you knew how to do this the long manual method compiling it.  Not important though since I got it working. 👍

**Comment by odeke-em** [comment]
Not a problem @nassausky. 

In order to develop drive I use the manual method but since you were having trouble the one liner was the remedy. However, since you are interested, here you go:
1. Please go into the directory that contains drive, on Unix systems it is: $GOPATH/src/github.com/odeke-em/drive, on Windows, it should be the equivalent but under $GOPATH and of course the path separators are different ;)
2. Once in that directory
```shell
go build -o drive_local ./cmd/drive
```
and that should build the binary to `drive_local` (which of course you could change the name of to anything), in your current working directory.
